const birdCodes = ["ABTO",
    "ACFL",
    "ACWO",
    "AFSI",
    "AKEK",
    "AKIA",
    "AKIK",
    "AKOH",
    "ALFL",
    "ALTE",
    "ALHU",
    "ALOR",
    "AMAU",
    "AMKI",
    "AMAV",
    "AMBI",
    "ABDU",
    "AMCO",
    "AMCR",
    "AMDI",
    "AMFL",
    "AMGP",
    "AMGO",
    "AMKE",
    "AMOY",
    "AMPI",
    "AMRE",
    "AMRO",
    "ATTW",
    "ATSP",
    "AWPE",
    "AMWI",
    "AMWO",
    "ATMG",
    "ANMU",
    "ANHI",
    "ANIA",
    "ANHU",
    "ANNI",
    "ANPS",
    "APAP",
    "APFA",
    "ARLO",
    "ARTE",
    "ARWA",
    "ARWO",
    "ATFL",
    "ASSP",
    "ABFL",
    "ASRF",
    "ATPU",
    "AUOR",
    "AUSH",
    "AZTH",
    "BACS",
    "BAWA",
    "BAMO",
    "BAHS",
    "BAWO",
    "BATE",
    "BASA",
    "BAIS",
    "BAEA",
    "BAOR",
    "BANA",
    "BSTP",
    "BTPI",
    "BANS",
    "BTTH",
    "BANO",
    "BARS",
    "BARG",
    "BASH",
    "BADO",
    "BAGO",
    "BTGO",
    "BBWA",
    "BEGU",
    "BESP",
    "BEVI",
    "BEKI",
    "BETH",
    "BEPE",
    "BEHU",
    "BEWR",
    "BITH",
    "BIOO",
    "BLFR",
    "BLGU",
    "BLAK",
    "BLMA",
    "BLNO",
    "BLOY",
    "BLPH",
    "BLRA",
    "BLRF",
    "BLSC",
    "BLSK",
    "BLSP",
    "BLSW",
    "BLTE",
    "BLTU",
    "BLVU",
    "BAWW",
    "BBOR",
    "BBWO",
    "BBPL",
    "BBSP",
    "BBWD",
    "BBCU",
    "BBMA",
    "BBAL",
    "BLBW",
    "BCCH",
    "BCGN",
    "BCPE",
    "BCVI",
    "BCHU",
    "BCSP",
    "BCTI",
    "BCNH",
    "BFGR",
    "BFAL",
    "BHGR",
    "BHGU",
    "BHNT",
    "BLKI",
    "BNST",
    "BLPW",
    "BTGN",
    "BLTG",
    "BTGU",
    "BTBW",
    "BTYW",
    "BTNW",
    "BTSP",
    "BVOR",
    "BVSH",
    "BWVI",
    "BWPE",
    "BWST",
    "BLBU",
    "BLGR",
    "BLJA",
    "BLMO",
    "BAWS",
    "BFBO",
    "BGGN",
    "BGNO",
    "BHVI",
    "BLUE",
    "BTMG",
    "BWTE",
    "BWWA",
    "BREW",
    "BTGR",
    "BOBO",
    "BOWA",
    "BOGU",
    "BOPE",
    "BOCH",
    "BOOW",
    "BOSP",
    "BRAM",
    "BRAC",
    "BRAN",
    "BRBL",
    "BRSP",
    "BRTE",
    "BRTI",
    "BTCU",
    "BBIH",
    "BBIS",
    "BTHU",
    "BWHA",
    "BROC",
    "BRBO",
    "BRCR",
    "BRJA",
    "BRNO",
    "BRPE",
    "BROS",
    "BRTH",
    "BBSO",
    "BCRF",
    "BCMA",
    "BCFL",
    "BHCO",
    "BHNU",
    "BRYS",
    "BBEH",
    "BBFL",
    "BBSA",
    "BCNI",
    "BUFF",
    "BULS",
    "BUOR",
    "BUPE",
    "BUHU",
    "BUOW",
    "BUSH",
    "CACG",
    "CACW",
    "CACO",
    "CAGN",
    "CAGU",
    "CAQU",
    "CASJ",
    "CATH",
    "CALT",
    "CAHU",
    "CANG",
    "CAJA",
    "CAWA",
    "CANV",
    "CANT",
    "CANW",
    "CMWA",
    "CVSH",
    "CACH",
    "CAPA",
    "CARW",
    "CATE",
    "CACR",
    "CAAU",
    "CAFI",
    "CAKI",
    "CASP",
    "CAVI",
    "CAEG",
    "CASW",
    "CEDW",
    "CERW",
    "CHAL",
    "CHMU",
    "CBCH",
    "CBSA",
    "CCLO",
    "CSWA",
    "CHRA",
    "CHSW",
    "CHEG",
    "CHPH",
    "CHIS",
    "CHSP",
    "CHSH",
    "CWWI",
    "CHUK",
    "CIHU",
    "CITE",
    "CIWA",
    "CLRA",
    "CLGR",
    "CLNU",
    "CCSP",
    "CCTH",
    "CLSW",
    "COLW",
    "COFF",
    "COPL",
    "COBH",
    "CCHA",
    "CCHI",
    "CCRA",
    "COCU",
    "COEI",
    "COGA",
    "COGO",
    "COGR",
    "COMG",
    "CGDO",
    "COGU",
    "COHM",
    "COLO",
    "COME",
    "COMO",
    "COMU",
    "COMY",
    "CONI",
    "COPA",
    "COMP",
    "COPO",
    "CORA",
    "CORE",
    "CREH",
    "CRET",
    "CRPL",
    "CORO",
    "COSA",
    "COSC",
    "COMS",
    "COSN",
    "COSW",
    "COTE",
    "COMW",
    "CWPI",
    "COYE",
    "CONW",
    "COPE",
    "COHA",
    "COFL",
    "CORC",
    "CORS",
    "COHU",
    "COKI",
    "CRHA",
    "CRMU",
    "CCWA",
    "CRAU",
    "CRCA",
    "CCGR",
    "CRTH",
    "CSFL",
    "CUMA",
    "CUPE",
    "CUVI",
    "CUSA",
    "CBTH",
    "DBCU",
    "DEJU",
    "DSFL",
    "DICK",
    "DCCO",
    "DSTK",
    "DTKI",
    "DOVE",
    "DOWO",
    "DUNL",
    "DUFL",
    "DUGR",
    "DUTH",
    "DUWA",
    "DCFL",
    "EAGR",
    "EAQU",
    "EABL",
    "EAKI",
    "EAME",
    "EAPH",
    "EASO",
    "ESBD",
    "EATO",
    "EWPW",
    "EAWP",
    "EYWA",
    "EGGO",
    "ELTE",
    "ELTR",
    "ELOW",
    "EMGO",
    "ERFR",
    "ESCU",
    "EUBB",
    "EUBU",
    "EUCD",
    "EUCO",
    "EUCU",
    "EUDO",
    "EHOB",
    "EHOO",
    "EUJA",
    "EUKE",
    "EUOY",
    "EUSI",
    "EUSK",
    "ETSP",
    "EUWI",
    "EUWO",
    "EUWR",
    "EUGP",
    "EURO",
    "EUST",
    "EUSP",
    "EUTD",
    "EVGR",
    "EYTH",
    "FADU",
    "FTWA",
    "FECU",
    "FEPE",
    "FEHA",
    "FEPO",
    "FISP",
    "FIEL",
    "FICR",
    "FSSP",
    "FCTA",
    "FLOW",
    "FFSH",
    "FLSJ",
    "FTFL",
    "FTSP",
    "FTSW",
    "FOTE",
    "FOSP",
    "FRGU",
    "FUWD",
    "GADW",
    "GAQU",
    "GARG",
    "GIWO",
    "GIFL",
    "GLGU",
    "GWGU",
    "GLIB",
    "GOEA",
    "GCWA",
    "GCKI",
    "GCSP",
    "GCRW",
    "GFWO",
    "GWWA",
    "GRWA",
    "GRSP",
    "GRBU",
    "GRCA",
    "GRFL",
    "GRAF",
    "GRHA",
    "GRAH",
    "GRAK",
    "GRNI",
    "GRAP",
    "GRSF",
    "GRVI",
    "GRAW",
    "GBAT",
    "GYBM",
    "GCTH",
    "GCBE",
    "GCRF",
    "GCYE",
    "GFPE",
    "GHCH",
    "GHGU",
    "GRGO",
    "GSFL",
    "GTTA",
    "GRAU",
    "GBHA",
    "GBBG",
    "GBHE",
    "GRCO",
    "GCFL",
    "GCTE",
    "GREG",
    "GREF",
    "GGOW",
    "GHOW",
    "GKIS",
    "GRKN",
    "GRSH",
    "GRSK",
    "GSWO",
    "GRAM",
    "GRKF",
    "GNLA",
    "GRPE",
    "GRPC",
    "GRRO",
    "GRSG",
    "GSAP",
    "GRSC",
    "GWFG",
    "GRYE",
    "GTGR",
    "GRHE",
    "GRJA",
    "GKIN",
    "GREP",
    "GRSA",
    "GNBM",
    "GREL",
    "GTTO",
    "GWTE",
    "GBAN",
    "GUMU",
    "GBTE",
    "GUSG",
    "GYRF",
    "HAWO",
    "HAFL",
    "HADU",
    "HASH",
    "HASP",
    "HAAK",
    "HAAM",
    "HCRE",
    "HAEL",
    "HAMA",
    "HAOO",
    "HACO",
    "HCRO",
    "HAWD",
    "HAGO",
    "HAWH",
    "HAPE",
    "HARA",
    "HAWF",
    "HEEG",
    "HESP",
    "HETA",
    "HEPE",
    "HETH",
    "HEWA",
    "HERG",
    "HISN",
    "HORE",
    "HOCR",
    "HOME",
    "HOOR",
    "HOWA",
    "HBKI",
    "HOGR",
    "HOLA",
    "HOPU",
    "HOFI",
    "HOSP",
    "HOWR",
    "HUGO",
    "HUVI",
    "HWAM",
    "ICGU",
    "IIWI",
    "INDO",
    "INTE",
    "INPE",
    "INBU",
    "INEG",
    "ISCA",
    "ISSJ",
    "IVGU",
    "IBWO",
    "JABI",
    "JASN",
    "JABW",
    "JASP",
    "JOPE",
    "JFPE",
    "JUTI",
    "KAKA",
    "KAPH",
    "KAMA",
    "KLWA",
    "KAAK",
    "KAAM",
    "KAEL",
    "KANU",
    "KAOO",
    "KEGU",
    "KEWA",
    "KEPE",
    "KWQD",
    "KILL",
    "KIEI",
    "KIRA",
    "KIOE",
    "KIWA",
    "KIMU",
    "KOGR",
    "LSFL",
    "LABD",
    "LBWO",
    "LANH",
    "LANW",
    "LALO",
    "LBTE",
    "LARB",
    "LASP",
    "LAGU",
    "LAGO",
    "LAAL",
    "LAYD",
    "LAFI",
    "LAYH",
    "LARA",
    "LAZB",
    "LESP",
    "LEAU",
    "LEBI",
    "LEFL",
    "LEGR",
    "LESA",
    "LSTP",
    "LETE",
    "LCSP",
    "LCTH",
    "LEAK",
    "LBBG",
    "LEFR",
    "LEGO",
    "LEKF",
    "LENI",
    "LEPC",
    "LSAP",
    "LESC",
    "LWFG",
    "LEWH",
    "LEYE",
    "LEWO",
    "LMAL",
    "LIMP",
    "LISP",
    "LBHE",
    "LIBU",
    "LICU",
    "LIEG",
    "LIGU",
    "LRPL",
    "LIST",
    "LITE",
    "LOKI",
    "LOSH",
    "LBCU",
    "LBDO",
    "LBMU",
    "LBTH",
    "LEOW",
    "LLBU",
    "LTDU",
    "LTJA",
    "LTST",
    "LOWA",
    "LUHU",
    "LUWA",
    "MGWA",
    "MAFR",
    "MAWA",
    "MALL",
    "MACU",
    "MANS",
    "MASH",
    "MAGO",
    "MAMU",
    "MASW",
    "MASA",
    "MAWR",
    "MABO",
    "MADU",
    "MATI",
    "MAAK",
    "MAAL",
    "MANU",
    "MAPA",
    "MNAK",
    "MKBU",
    "MERL",
    "MECH",
    "MEDU",
    "MEJA",
    "MEVI",
    "MWPW",
    "MGRW",
    "MILL",
    "MIKI",
    "MITH",
    "MIPA",
    "MOPA",
    "MONQ",
    "MOSE",
    "MODU",
    "MOOW",
    "MOPE",
    "MOBL",
    "MOCH",
    "MOPL",
    "MOUQ",
    "MODO",
    "MOWA",
    "MUFL",
    "MUPE",
    "MUDU",
    "MUSW",
    "NAPA",
    "NAFL",
    "NAWA",
    "NATH",
    "NABO",
    "NESP",
    "NECO",
    "NESH",
    "NIFI",
    "NOBT",
    "NOBO",
    "NOBB",
    "NOCA",
    "NOFL",
    "NOFU",
    "NOGA",
    "NOGP",
    "NOGO",
    "NOHA",
    "NHOW",
    "NOJA",
    "NOLA",
    "NOMO",
    "NOPA",
    "NOPI",
    "NOPO",
    "NRWS",
    "NSWO",
    "NSHO",
    "NSHR",
    "NOWA",
    "NOWH",
    "NUWO",
    "NUFL",
    "OAKE",
    "OAKI",
    "OAAL",
    "OAAM",
    "OAEL",
    "OANU",
    "OAOO",
    "OATI",
    "OLSP",
    "OLWA",
    "OBPI",
    "OSFL",
    "OLOM",
    "OMAO",
    "OBNT",
    "OCWA",
    "OROR",
    "ORCU",
    "ORGR",
    "ORPR",
    "ORSO",
    "ORTD",
    "OSPR",
    "OU",
    "OVEN",
    "PAGP",
    "PALO",
    "PAWR",
    "PSFL",
    "PBCR",
    "PABU",
    "PARE",
    "PALI",
    "PALB",
    "PGWA",
    "PAGU",
    "PLEW",
    "PARO",
    "PAWA",
    "PAAU",
    "PAJA",
    "PAPE",
    "PAPI",
    "PEPI",
    "PESA",
    "PECO",
    "PEFA",
    "PHAI",
    "PHVI",
    "PIWH",
    "PBGR",
    "PIGU",
    "PIWO",
    "PIBU",
    "PINF",
    "PIGR",
    "PISI",
    "PIWA",
    "PFGO",
    "PFSH",
    "PTSN",
    "PIJA",
    "PIPL",
    "PIRF",
    "PLCH",
    "PCST",
    "PLVI",
    "POJA",
    "POUL",
    "PRFA",
    "PRAW",
    "PROW",
    "PRPE",
    "PUAI",
    "PUFI",
    "PUGA",
    "PUMA",
    "PUSA",
    "PUSW",
    "PYNU",
    "PYRR",
    "RAZO",
    "REAV",
    "RECR",
    "REJU",
    "REKN",
    "REPH",
    "RBSH",
    "RBWO",
    "RBLE",
    "RBPI",
    "RBTR",
    "RBME",
    "RBNU",
    "RBSA",
    "RCWO",
    "RCCA",
    "RCPA",
    "REEG",
    "REVI",
    "RFCO",
    "RFWA",
    "RFBL",
    "RFBO",
    "RFFA",
    "REDH",
    "RHWO",
    "RLHO",
    "RLKI",
    "RLTH",
    "RNSA",
    "RNGR",
    "RNPH",
    "RNST",
    "RSHA",
    "RTHA",
    "RTTR",
    "RTLO",
    "RTPI",
    "RVBU",
    "RWBU",
    "REDW",
    "RWBL",
    "REBU",
    "RHAU",
    "RIRA",
    "RBGU",
    "RIKI",
    "RISP",
    "RNDU",
    "RNEP",
    "RIWA ",
    "RIHU",
    "ROHA",
    "ROPI",
    "ROPT",
    "ROSA",
    "ROWR",
    "ROSP",
    "ROST",
    "RBGR",
    "RRPA",
    "RTBE",
    "ROGO",
    "ROGU",
    "RFLO",
    "RLHA",
    "ROYT",
    "RCKI",
    "RTHU",
    "RUDU",
    "RGDO",
    "RUQD",
    "RUTU",
    "RUFF",
    "RUGR",
    "RUHU",
    "RBRO",
    "RCWA",
    "RCSP",
    "RNWR",
    "RTRO",
    "RWSP",
    "RUBU",
    "RUBL",
    "SAGU",
    "SAFI",
    "SATH",
    "SABS",
    "SALS",
    "SAAL",
    "SAND",
    "SACR",
    "SATE",
    "SAVS",
    "SAPH",
    "SCQU",
    "SBMU",
    "SNPI",
    "SCIB",
    "SCTA",
    "STFL",
    "SCOR",
    "SCMU",
    "SESP",
    "SEWA",
    "SEWR",
    "SEPL",
    "SESA",
    "SSHA",
    "STGR",
    "SPTS",
    "SHCO",
    "SBDO",
    "SBIG",
    "SEOW",
    "STAL",
    "STHA",
    "STTS",
    "SIAC",
    "SBRO",
    "SIRU",
    "SIWR",
    "STRE",
    "SBAG",
    "SBCU",
    "SBEL",
    "SMEW",
    "SMLO",
    "SBAN",
    "SNKI",
    "SNBU",
    "SNGO",
    "SNEG",
    "SNOW",
    "SNPL",
    "SOFL",
    "SOSA",
    "SOSN",
    "SOSP",
    "SOTH",
    "SOGR",
    "SOSH",
    "SOTE",
    "SORA",
    "SPSK",
    "SOMA",
    "SPEI",
    "SBSA",
    "SBOR",
    "SPDO",
    "SPFL",
    "SPOW",
    "SPRA",
    "SPRE",
    "SPSA",
    "SPTO",
    "SPPI",
    "SPGR",
    "STPE",
    "STSC",
    "STEI",
    "STJA",
    "STSE",
    "STSA",
    "STON",
    "SBAO",
    "STRS",
    "STOW",
    "SBFL",
    "SUTA",
    "SUNG",
    "SUSC",
    "SURF",
    "SWHA",
    "SWTH",
    "SWWA",
    "STGU",
    "STKI",
    "SWSP",
    "SSTP",
    "TAPE",
    "TABG",
    "TAFL",
    "TACR",
    "TSBL",
    "TEST",
    "TEWA",
    "TESA",
    "TBKI",
    "TBLO",
    "TBMU",
    "TBPA",
    "TBVI",
    "TBWA ",
    "TOSO",
    "TOSP",
    "TOWA",
    "TRPI",
    "TRES",
    "TRBL",
    "TRHE",
    "TRMU",
    "TRPE",
    "TRSP",
    "TRKI",
    "TRPA",
    "TRUS",
    "TUDU",
    "TUFL",
    "TUPU",
    "TUTI",
    "TUBG",
    "TUSW",
    "TUVU",
    "UAIH",
    "UPSA",
    "VABU",
    "VATH",
    "VAFL",
    "VASW",
    "VEER",
    "VERD",
    "VEFL",
    "VESP",
    "VCHU",
    "VGSW",
    "VIRA",
    "VIWA",
    "WAAL",
    "WATA",
    "WAVI",
    "WAWE",
    "WRSP",
    "WTSH",
    "WEBL",
    "WEGR",
    "WEGU",
    "WEKI",
    "WEME",
    "WERH",
    "WESA",
    "WESO",
    "WESP",
    "WETA",
    "WEWP",
    "WHIM",
    "WHAU",
    "WHSO",
    "WHST",
    "WHIB",
    "WHTT",
    "WHWA",
    "WBNU",
    "WCAL",
    "WCHP",
    "WCPE",
    "WCSW",
    "WCEL",
    "WCPI",
    "WCSP",
    "WEHU",
    "WEVI",
    "WFIB",
    "WFSP",
    "WHWO",
    "WNPE",
    "WRSA",
    "WRSH",
    "WTEA",
    "WTHA",
    "WTKI",
    "WTPT",
    "WTTR",
    "WTNE",
    "WTSP",
    "WTSW",
    "WTTH",
    "WTDO",
    "WWCR",
    "WWDO",
    "WWPA",
    "WWSC",
    "WWTE",
    "WHOS",
    "WHCR",
    "WITU",
    "WILL",
    "WISA",
    "WIFL",
    "WIPT",
    "WILW",
    "WIPH",
    "WIPL",
    "WISN",
    "WISP",
    "WIWA",
    "WIWR",
    "WODU",
    "WOSA",
    "WOST",
    "WOTH",
    "WOWA",
    "WOSJ",
    "WEWA",
    "WOSP",
    "WREN",
    "XAHU",
    "YEBI",
    "YEGR",
    "YERA",
    "YEWA",
    "YBFL",
    "YBSA",
    "YBCA",
    "YBCU",
    "YBLO",
    "YBMA",
    "YBSB",
    "YBCH",
    "YBWB",
    "YBWA",
    "YCPA",
    "YCNH",
    "YEJU",
    "YFGR",
    "YFGU",
    "YFCA",
    "YGVI",
    "YHBL",
    "YLGU",
    "YNAL",
    "YRWA",
    "YTBU",
    "YTVI",
    "YTWA",
    "YUVI",
    "ZEBD",
    "ZEND",
    "ZIPE",
    "ZTHA"];

const birdNames = [
    "Abert's Towhee",
    "Acadian Flycatcher",
    "Acorn Woodpecker",
    "African Silverbill",
    "Akekee",
    "Akiapolaau",
    "Akikiki",
    "Akohekohe",
    "Alder Flycatcher",
    "Aleutian Tern",
    "Allen's Hummingbird",
    "Altamira Oriole",
    "Amaui",
    "Amazon Kingfisher",
    "American Avocet",
    "American Bittern",
    "American Black Duck",
    "American Coot",
    "American Crow",
    "American Dipper",
    "American Flamingo",
    "American Golden-Plover",
    "American Goldfinch",
    "American Kestrel",
    "American Oystercatcher",
    "American Pipit",
    "American Redstart",
    "American Robin",
    "American Three-toed Woodpecker",
    "American Tree Sparrow",
    "American White Pelican",
    "American Wigeon",
    "American Woodcock",
    "Amethyst-throated Mountain-gem",
    "Ancient Murrelet",
    "Anhinga",
    "Anianiau",
    "Anna's Hummingbird",
    "Antillean Nighthawk",
    "Antillean Palm-Swift",
    "Apapane",
    "Aplomado Falcon",
    "Arctic Loon",
    "Arctic Tern",
    "Arctic Warbler",
    "Arizona Woodpecker",
    "Ash-throated Flycatcher",
    "Ashy Storm-Petrel",
    "Asian Brown Flycatcher",
    "Asian Rosy-Finch",
    "Atlantic Puffin",
    "Audubon's Oriole",
    "Audubon's Shearwater",
    "Aztec Thrush",
    "Bachman's Sparrow",
    "Bachman's Warbler",
    "Bahama Mockingbird",
    "Bahama Swallow",
    "Bahama Woodstar",
    "Baikal Teal",
    "Baird's Sandpiper",
    "Baird's Sparrow",
    "Bald Eagle",
    "Baltimore Oriole",
    "Bananaquit",
    "Band-rumped Storm-Petrel",
    "Band-tailed Pigeon",
    "Bank Swallow",
    "Bare-throated Tiger-Heron",
    "Barn Owl",
    "Barn Swallow",
    "Barnacle Goose",
    "Barolo Shearwater",
    "Barred Owl",
    "Barrow's Goldeneye",
    "Bar-tailed Godwit",
    "Bay-breasted Warbler",
    "Belcher's Gull",
    "Bell's Sparrow",
    "Bell's Vireo",
    "Belted Kingfisher",
    "Bendire's Thrasher",
    "Bermuda Petrel",
    "Berylline Hummingbird",
    "Bewick's Wren",
    "Bicknell's Thrush",
    "Bishop's Oo",
    "Black Francolin",
    "Black Guillemot",
    "Black Kite",
    "Black Mamo",
    "Black Noddy",
    "Black Oystercatcher",
    "Black Phoebe",
    "Black Rail",
    "Black Rosy-Finch",
    "Black Scoter",
    "Black Skimmer",
    "Black Storm-Petrel",
    "Black Swift",
    "Black Tern",
    "Black Turnstone",
    "Black Vulture",
    "Black-and-white Warbler",
    "Black-backed Oriole",
    "Black-backed Woodpecker",
    "Black-bellied Plover",
    "Black-bellied Storm-Petrel",
    "Black-bellied Whistling-Duck",
    "Black-billed Cuckoo",
    "Black-billed Magpie",
    "Black-browed Albatross",
    "Blackburnian Warbler",
    "Black-capped Chickadee",
    "Black-capped Gnatcatcher",
    "Black-capped Petrel",
    "Black-capped Vireo",
    "Black-chinned Hummingbird",
    "Black-chinned Sparrow",
    "Black-crested Titmouse",
    "Black-crowned Night-Heron",
    "Black-faced Grassquit",
    "Black-footed Albatross",
    "Black-headed Grosbeak",
    "Black-headed Gull",
    "Black-headed Nightingale-Thrush",
    "Black-legged Kittiwake",
    "Black-necked Stilt",
    "Blackpoll Warbler",
    "Black-tailed Gnatcatcher",
    "Black-tailed Godwit",
    "Black-tailed Gull",
    "Black-throated Blue Warbler",
    "Black-throated Gray Warbler",
    "Black-throated Green Warbler",
    "Black-throated Sparrow",
    "Black-vented Oriole",
    "Black-vented Shearwater",
    "Black-whiskered Vireo",
    "Black-winged Petrel",
    "Black-winged Stilt",
    "Blue Bunting",
    "Blue Grosbeak",
    "Blue Jay",
    "Blue Mockingbird",
    "Blue-and-white Swallow",
    "Blue-footed Booby",
    "Blue-gray Gnatcatcher",
    "Blue-gray Noddy",
    "Blue-headed Vireo",
    "Bluethroat",
    "Blue-throated Mountain-gem",
    "Blue-winged Teal",
    "Blue-winged Warbler",
    "Blyth's Reed Warbler",
    "Boat-tailed Grackle",
    "Bobolink",
    "Bohemian Waxwing",
    "Bonaparte's Gull",
    "Bonin Petrel",
    "Boreal Chickadee",
    "Boreal Owl",
    "Botteri's Sparrow",
    "Brambling",
    "Brandt's Cormorant",
    "Brant",
    "Brewer's Blackbird",
    "Brewer's Sparrow",
    "Bridled Tern",
    "Bridled Titmouse",
    "Bristle-thighed Curlew",
    "Broad-billed Hummingbird",
    "Broad-billed Sandpiper",
    "Broad-tailed Hummingbird",
    "Broad-winged Hawk",
    "Bronzed Cowbird",
    "Brown Booby",
    "Brown Creeper",
    "Brown Jay",
    "Brown Noddy",
    "Brown Pelican",
    "Brown Shrike",
    "Brown Thrasher",
    "Brown-backed Solitaire",
    "Brown-capped Rosy-Finch",
    "Brown-chested Martin",
    "Brown-crested Flycatcher",
    "Brown-headed Cowbird",
    "Brown-headed Nuthatch",
    "Bryan's Shearwater",
    "Buff-bellied Hummingbird",
    "Buff-breasted Flycatcher",
    "Buff-breasted Sandpiper",
    "Buff-collared Nightjar",
    "Bufflehead",
    "Buller's Shearwater",
    "Bullock's Oriole",
    "Bulwer's Petrel",
    "Bumblebee Hummingbird",
    "Burrowing Owl",
    "Bushtit",
    "Cackling Goose",
    "Cactus Wren",
    "California Condor",
    "California Gnatcatcher",
    "California Gull",
    "California Quail",
    "California Scrub-Jay",
    "California Thrasher",
    "California Towhee",
    "Calliope Hummingbird",
    "Canada Goose",
    "Canada Jay",
    "Canada Warbler",
    "Canvasback",
    "Canyon Towhee",
    "Canyon Wren",
    "Cape May Warbler",
    "Cape Verde Shearwater",
    "Carolina Chickadee",
    "Carolina Parakeet",
    "Carolina Wren",
    "Caspian Tern",
    "Cassia Crossbill",
    "Cassin's Auklet",
    "Cassin's Finch",
    "Cassin's Kingbird",
    "Cassin's Sparrow",
    "Cassin's Vireo",
    "Cattle Egret",
    "Cave Swallow",
    "Cedar Waxwing",
    "Cerulean Warbler",
    "Chatham Albatross",
    "Chestnut Munia",
    "Chestnut-backed Chickadee",
    "Chestnut-bellied Sandgrouse",
    "Chestnut-collared Longspur",
    "Chestnut-sided Warbler",
    "Chihuahuan Raven",
    "Chimney Swift",
    "Chinese Egret",
    "Chinese Pond-Heron",
    "Chinese Sparrowhawk",
    "Chipping Sparrow",
    "Christmas Shearwater",
    "Chuck-will's-widow",
    "Chukar",
    "Cinnamon Hummingbird",
    "Cinnamon Teal",
    "Citrine Wagtail",
    "Clapper Rail",
    "Clark's Grebe",
    "Clark's Nutcracker",
    "Clay-colored Sparrow",
    "Clay-colored Thrush",
    "Cliff Swallow",
    "Colima Warbler",
    "Collared Forest-Falcon",
    "Collared Plover",
    "Common Black Hawk",
    "Common Chaffinch",
    "Common Chiffchaff",
    "Common Crane",
    "Common Cuckoo",
    "Common Eider",
    "Common Gallinule",
    "Common Goldeneye",
    "Common Grackle",
    "Common Greenshank",
    "Common Ground Dove",
    "Common Gull",
    "Common House-Martin",
    "Common Loon",
    "Common Merganser",
    "Common Moorhen",
    "Common Murre",
    "Common Myna",
    "Common Nighthawk",
    "Common Pauraque",
    "Common Pochard",
    "Common Poorwill",
    "Common Raven",
    "Common Redpoll",
    "Common Redshank",
    "Common Redstart",
    "Common Ringed Plover",
    "Common Rosefinch",
    "Common Sandpiper",
    "Common Scoter",
    "Common Shelduck",
    "Common Snipe",
    "Common Swift",
    "Common Tern",
    "Common Waxbill",
    "Common Wood Pigeon",
    "Common Yellowthroat",
    "Connecticut Warbler",
    "Cook's Petrel",
    "Cooper's Hawk",
    "Cordilleran Flycatcher",
    "Corn Crake",
    "Cory's Shearwater",
    "Costa's Hummingbird",
    "Couch's Kingbird",
    "Crane Hawk",
    "Craveri's Murrelet",
    "Crescent-chested Warbler",
    "Crested Auklet",
    "Crested Caracara",
    "Crimson-collared Grosbeak",
    "Crissal Thrasher",
    "Crowned Slaty Flycatcher",
    "Cuban Martin",
    "Cuban Pewee",
    "Cuban Vireo",
    "Curlew Sandpiper",
    "Curve-billed Thrasher",
    "Dark-billed Cuckoo",
    "Dark-eyed Junco",
    "Dark-sided Flycatcher",
    "Dickcissel",
    "Double-crested Cormorant",
    "Double-striped Thick-knee",
    "Double-toothed Kite",
    "Dovekie",
    "Downy Woodpecker",
    "Dunlin",
    "Dusky Flycatcher",
    "Dusky Grouse",
    "Dusky Thrush",
    "Dusky Warbler",
    "Dusky-capped Flycatcher",
    "Eared Grebe",
    "Eared Quetzal",
    "Eastern Bluebird",
    "Eastern Kingbird",
    "Eastern Meadowlark",
    "Eastern Phoebe",
    "Eastern Screech-Owl",
    "Eastern Spot-billed Duck",
    "Eastern Towhee",
    "Eastern Whip-poor-will",
    "Eastern Wood-Pewee",
    "Eastern Yellow Wagtail",
    "Egyptian Goose",
    "Elegant Tern",
    "Elegant Trogon",
    "Elf Owl",
    "Emperor Goose",
    "Erckel's Francolin",
    "Eskimo Curlew",
    "Eurasian Blackbird",
    "Eurasian Bullfinch",
    "Eurasian Collared-Dove",
    "Eurasian Coot",
    "Eurasian Curlew",
    "Eurasian Dotterel",
    "Eurasian Hobby",
    "Eurasian Hoopoe",
    "Eurasian Jackdaw",
    "Eurasian Kestrel",
    "Eurasian Oystercatcher",
    "Eurasian Siskin",
    "Eurasian Skylark",
    "Eurasian Tree Sparrow",
    "Eurasian Wigeon",
    "Eurasian Woodcock",
    "Eurasian Wryneck",
    "European Golden-Plover",
    "European Robin",
    "European Starling",
    "European Storm-Petrel",
    "European Turtle-Dove",
    "Evening Grosbeak",
    "Eyebrowed Thrush",
    "Falcated Duck",
    "Fan-tailed Warbler",
    "Far Eastern Curlew",
    "Fea's Petrel",
    "Ferruginous Hawk",
    "Ferruginous Pygmy-Owl",
    "Field Sparrow",
    "Fieldfare",
    "Fish Crow",
    "Five-striped Sparrow",
    "Flame-colored Tanager",
    "Flammulated Owl",
    "Flesh-footed Shearwater",
    "Florida Scrub-Jay",
    "Fork-tailed Flycatcher",
    "Fork-tailed Storm-Petrel",
    "Fork-tailed Swift",
    "Forster's Tern",
    "Fox Sparrow",
    "Franklin's Gull",
    "Fulvous Whistling-Duck",
    "Gadwall",
    "Gambel's Quail",
    "Garganey",
    "Gila Woodpecker",
    "Gilded Flicker",
    "Glaucous Gull",
    "Glaucous-winged Gull",
    "Glossy Ibis",
    "Golden Eagle",
    "Golden-cheeked Warbler",
    "Golden-crowned Kinglet",
    "Golden-crowned Sparrow",
    "Golden-crowned Warbler",
    "Golden-fronted Woodpecker",
    "Golden-winged Warbler",
    "Grace's Warbler",
    "Grasshopper Sparrow",
    "Gray Bunting",
    "Gray Catbird",
    "Gray Flycatcher",
    "Gray Francolin",
    "Gray Hawk",
    "Gray Heron",
    "Gray Kingbird",
    "Gray Nightjar",
    "Gray Partridge",
    "Gray Silky-flycatcher",
    "Gray Vireo",
    "Gray Wagtail",
    "Gray-backed Tern",
    "Gray-breasted Martin",
    "Gray-cheeked Thrush",
    "Gray-collared Becard",
    "Gray-crowned Rosy-Finch",
    "Gray-crowned Yellowthroat",
    "Gray-faced Petrel",
    "Gray-headed Chickadee",
    "Gray-hooded Gull",
    "Graylag Goose",
    "Gray-streaked Flycatcher",
    "Gray-tailed Tattler",
    "Great Auk",
    "Great Black Hawk",
    "Great Black-backed Gull",
    "Great Blue Heron",
    "Great Cormorant",
    "Great Crested Flycatcher",
    "Great Crested Tern",
    "Great Egret",
    "Great Frigatebird",
    "Great Gray Owl",
    "Great Horned Owl",
    "Great Kiskadee",
    "Great Knot",
    "Great Shearwater",
    "Great Skua",
    "Great Spotted Woodpecker",
    "Greater Amakihi",
    "Greater Koa-Finch",
    "Greater Necklaced Laughingthrush",
    "Greater Pewee",
    "Greater Prairie-Chicken",
    "Greater Roadrunner",
    "Greater Sage-Grouse",
    "Greater Sand-Plover",
    "Greater Scaup",
    "Greater White-fronted Goose",
    "Greater Yellowlegs",
    "Great-tailed Grackle",
    "Green Heron",
    "Green Jay",
    "Green Kingfisher",
    "Green Parakeet",
    "Green Sandpiper",
    "Green-breasted Mango",
    "Greenish Elaenia",
    "Green-tailed Towhee",
    "Green-winged Teal",
    "Groove-billed Ani",
    "Guadalupe Murrelet",
    "Gull-billed Tern",
    "Gunnison Sage-Grouse",
    "Gyrfalcon",
    "Hairy Woodpecker",
    "Hammond's Flycatcher",
    "Harlequin Duck",
    "Harris's Hawk",
    "Harris's Sparrow",
    "Hawaii Akepa",
    "Hawaii Amakihi",
    "Hawaii Creeper",
    "Hawaii Elepaio",
    "Hawaii Mamo",
    "Hawaii Oo",
    "Hawaiian Coot",
    "Hawaiian Crow",
    "Hawaiian Duck",
    "Hawaiian Goose",
    "Hawaiian Hawk",
    "Hawaiian Petrel",
    "Hawaiian Rail",
    "Hawfinch",
    "Heermann's Gull",
    "Henslow's Sparrow",
    "Hepatic Tanager",
    "Herald Petrel",
    "Hermit Thrush",
    "Hermit Warbler",
    "Herring Gull",
    "Himalayan Snowcock",
    "Hoary Redpoll",
    "Hooded Crane",
    "Hooded Merganser",
    "Hooded Oriole",
    "Hooded Warbler",
    "Hook-billed Kite",
    "Horned Grebe",
    "Horned Lark",
    "Horned Puffin",
    "House Finch",
    "House Sparrow",
    "House Wren",
    "Hudsonian Godwit",
    "Hutton's Vireo",
    "Hwamei",
    "Iceland Gull",
    "Iiwi",
    "Inca Dove",
    "Inca Tern",
    "Indian Peafowl",
    "Indigo Bunting",
    "Intermediate Egret",
    "Island Canary",
    "Island Scrub-Jay",
    "Ivory Gull",
    "Ivory-billed Woodpecker",
    "Jabiru",
    "Jack Snipe",
    "Japanese Bush-Warbler",
    "Java Sparrow",
    "Jouanin's Petrel",
    "Juan Fernandez Petrel",
    "Juniper Titmouse",
    "Kakawahie",
    "Kalij Pheasant",
    "Kamao",
    "Kamchatka Leaf Warbler",
    "Kauai Akialoa",
    "Kauai Amakihi",
    "Kauai Elepaio",
    "Kauai Nukupuu",
    "Kauai Oo",
    "Kelp Gull",
    "Kentucky Warbler",
    "Kermadec Petrel",
    "Key West Quail-Dove",
    "Killdeer",
    "King Eider",
    "King Rail",
    "Kioea",
    "Kirtland's Warbler",
    "Kittlitz's Murrelet",
    "Kona Grosbeak",
    "La Sagra's Flycatcher",
    "Labrador Duck",
    "Ladder-backed Woodpecker",
    "Lanai Hookbill",
    "Lanceolated Warbler",
    "Lapland Longspur",
    "Large-billed Tern",
    "Lark Bunting",
    "Lark Sparrow",
    "Laughing Gull",
    "Lawrence's Goldfinch",
    "Laysan Albatross",
    "Laysan Duck",
    "Laysan Finch",
    "Laysan Honeycreeper",
    "Laysan Rail",
    "Lazuli Bunting",
    "Leach's Storm-Petrel",
    "Least Auklet",
    "Least Bittern",
    "Least Flycatcher",
    "Least Grebe",
    "Least Sandpiper",
    "Least Storm-Petrel",
    "Least Tern",
    "LeConte's Sparrow",
    "LeConte's Thrasher",
    "Lesser Akialoa",
    "Lesser Black-backed Gull",
    "Lesser Frigatebird",
    "Lesser Goldfinch",
    "Lesser Koa-Finch",
    "Lesser Nighthawk",
    "Lesser Prairie-Chicken",
    "Lesser Sand-Plover",
    "Lesser Scaup",
    "Lesser White-fronted Goose",
    "Lesser Whitethroat",
    "Lesser Yellowlegs",
    "Lewis's Woodpecker",
    "Light-mantled Albatross",
    "Limpkin",
    "Lincoln's Sparrow",
    "Little Blue Heron",
    "Little Bunting",
    "Little Curlew",
    "Little Egret",
    "Little Gull",
    "Little Ringed Plover",
    "Little Stint",
    "Little Tern",
    "Loggerhead Kingbird",
    "Loggerhead Shrike",
    "Long-billed Curlew",
    "Long-billed Dowitcher",
    "Long-billed Murrelet",
    "Long-billed Thrasher",
    "Long-eared Owl",
    "Long-legged Buzzard",
    "Long-tailed Duck",
    "Long-tailed Jaeger",
    "Long-toed Stint",
    "Louisiana Waterthrush",
    "Lucifer Hummingbird",
    "Lucy's Warbler",
    "MacGillivray's Warbler",
    "Magnificent Frigatebird",
    "Magnolia Warbler",
    "Mallard",
    "Mangrove Cuckoo",
    "Mangrove Swallow",
    "Manx Shearwater",
    "Marbled Godwit",
    "Marbled Murrelet",
    "Mariana Swiftlet",
    "Marsh Sandpiper",
    "Marsh Wren",
    "Masked Booby",
    "Masked Duck",
    "Masked Tityra",
    "Maui Akepa",
    "Maui Alauahio",
    "Maui Nukupuu",
    "Maui Parrotbill",
    "Maui-nui Akialoa",
    "McKay's Bunting",
    "Merlin",
    "Mexican Chickadee",
    "Mexican Duck",
    "Mexican Jay",
    "Mexican Violetear",
    "Mexican Whip-poor-will",
    "Middendorff's Grasshopper Warbler",
    "Millerbird",
    "Mississippi Kite",
    "Mistle Thrush",
    "Mitred Parakeet",
    "Monk Parakeet",
    "Montezuma Quail",
    "Morelet's Seedeater",
    "Mottled Duck",
    "Mottled Owl",
    "Mottled Petrel",
    "Mountain Bluebird",
    "Mountain Chickadee",
    "Mountain Plover",
    "Mountain Quail",
    "Mourning Dove",
    "Mourning Warbler",
    "Mugimaki Flycatcher",
    "Murphy's Petrel",
    "Muscovy Duck",
    "Mute Swan",
    "Nanday Parakeet",
    "Narcissus Flycatcher",
    "Nashville Warbler",
    "Naumann's Thrush",
    "Nazca Booby",
    "Nelson's Sparrow",
    "Neotropic Cormorant",
    "Newell's Shearwater",
    "Nihoa Finch",
    "Northern Beardless-Tyrannulet",
    "Northern Bobwhite",
    "Northern Boobook",
    "Northern Cardinal",
    "Northern Flicker",
    "Northern Fulmar",
    "Northern Gannet",
    "Northern Giant-Petrel",
    "Northern Goshawk",
    "Northern Harrier",
    "Northern Hawk Owl",
    "Northern Jacana",
    "Northern Lapwing",
    "Northern Mockingbird",
    "Northern Parula",
    "Northern Pintail",
    "Northern Pygmy-Owl",
    "Northern Rough-winged Swallow",
    "Northern Saw-whet Owl",
    "Northern Shoveler",
    "Northern Shrike",
    "Northern Waterthrush",
    "Northern Wheatear",
    "Nuttall's Woodpecker",
    "Nutting's Flycatcher",
    "Oahu Akepa",
    "Oahu Akialoa",
    "Oahu Alauahio",
    "Oahu Amakihi",
    "Oahu Elepaio",
    "Oahu Nukupuu",
    "Oahu Oo",
    "Oak Titmouse",
    "Olive Sparrow",
    "Olive Warbler",
    "Olive-backed Pipit",
    "Olive-sided Flycatcher",
    "Olomao",
    "Omao",
    "Orange-billed Nightingale-Thrush",
    "Orange-crowned Warbler",
    "Orchard Oriole",
    "Oriental Cuckoo",
    "Oriental Greenfinch",
    "Oriental Pratincole",
    "Oriental Scops-Owl",
    "Oriental Turtle-Dove",
    "Osprey",
    "Ou",
    "Ovenbird",
    "Pacific Golden-Plover",
    "Pacific Loon",
    "Pacific Wren",
    "Pacific-slope Flycatcher",
    "Paint-billed Crake",
    "Painted Bunting",
    "Painted Redstart",
    "Palila",
    "Pallas's Bunting",
    "Pallas's Grasshopper Warbler",
    "Pallas's Gull",
    "Pallas's Leaf Warbler",
    "Pallas's Rosefinch",
    "Palm Warbler",
    "Parakeet Auklet",
    "Parasitic Jaeger",
    "Parkinson's Petrel",
    "Passenger Pigeon",
    "Pechora Pipit",
    "Pectoral Sandpiper",
    "Pelagic Cormorant",
    "Peregrine Falcon",
    "Phainopepla",
    "Philadelphia Vireo",
    "Pied Wheatear",
    "Pied-billed Grebe",
    "Pigeon Guillemot",
    "Pileated Woodpecker",
    "Pine Bunting",
    "Pine Flycatcher",
    "Pine Grosbeak",
    "Pine Siskin",
    "Pine Warbler",
    "Pink-footed Goose",
    "Pink-footed Shearwater",
    "Pin-tailed Snipe",
    "Pinyon Jay",
    "Piping Plover",
    "Piratic Flycatcher",
    "Plain Chachalaca",
    "Plain-capped Starthroat",
    "Plumbeous Vireo",
    "Pomarine Jaeger",
    "Poo-uli",
    "Prairie Falcon",
    "Prairie Warbler",
    "Prothonotary Warbler",
    "Providence Petrel",
    "Puaiohi",
    "Purple Finch",
    "Purple Gallinule",
    "Purple Martin",
    "Purple Sandpiper",
    "Purple Swamphen",
    "Pygmy Nuthatch",
    "Pyrrhuloxia",
    "Razorbill",
    "Red Avadavat",
    "Red Crossbill",
    "Red Junglefowl",
    "Red Knot",
    "Red Phalarope",
    "Red-backed Shrike",
    "Red-bellied Woodpecker",
    "Red-billed Leiothrix",
    "Red-billed Pigeon",
    "Red-billed Tropicbird",
    "Red-breasted Merganser",
    "Red-breasted Nuthatch",
    "Red-breasted Sapsucker",
    "Red-cockaded Woodpecker",
    "Red-crested Cardinal",
    "Red-crowned Parrot",
    "Reddish Egret",
    "Red-eyed Vireo",
    "Red-faced Cormorant",
    "Red-faced Warbler",
    "Red-flanked Bluetail",
    "Red-footed Booby",
    "Red-footed Falcon",
    "Redhead",
    "Red-headed Woodpecker",
    "Red-legged Honeycreeper",
    "Red-legged Kittiwake",
    "Red-legged Thrush",
    "Red-naped Sapsucker",
    "Red-necked Grebe",
    "Red-necked Phalarope",
    "Red-necked Stint",
    "Red-shouldered Hawk",
    "Red-tailed Hawk",
    "Red-tailed Tropicbird",
    "Red-throated Loon",
    "Red-throated Pipit",
    "Red-vented Bulbul",
    "Red-whiskered Bulbul",
    "Redwing",
    "Red-winged Blackbird",
    "Reed Bunting",
    "Rhinoceros Auklet",
    "Ridgway's Rail",
    "Ring-billed Gull",
    "Ringed Kingfisher",
    "Ringed Storm-Petrel",
    "Ring-necked Duck",
    "Ring-necked Pheasant",
    "River Warbler",
    "Rivoli's Hummingbird",
    "Roadside Hawk",
    "Rock Pigeon",
    "Rock Ptarmigan",
    "Rock Sandpiper",
    "Rock Wren",
    "Roseate Spoonbill",
    "Roseate Tern",
    "Rose-breasted Grosbeak",
    "Rose-ringed Parakeet",
    "Rose-throated Becard",
    "Ross's Goose",
    "Ross's Gull",
    "Rosy-faced Lovebird",
    "Rough-legged Hawk",
    "Royal Tern",
    "Ruby-crowned Kinglet",
    "Ruby-throated Hummingbird",
    "Ruddy Duck",
    "Ruddy Ground Dove",
    "Ruddy Quail-Dove",
    "Ruddy Turnstone",
    "Ruff",
    "Ruffed Grouse",
    "Rufous Hummingbird",
    "Rufous-backed Robin",
    "Rufous-capped Warbler",
    "Rufous-crowned Sparrow",
    "Rufous-necked Wood-Rail",
    "Rufous-tailed Robin",
    "Rufous-winged Sparrow",
    "Rustic Bunting",
    "Rusty Blackbird",
    "Sabine's Gull",
    "Saffron Finch",
    "Sage Thrasher",
    "Sagebrush Sparrow",
    "Saltmarsh Sparrow",
    "Salvin's Albatross",
    "Sanderling",
    "Sandhill Crane",
    "Sandwich Tern",
    "Savannah Sparrow",
    "Say's Phoebe",
    "Scaled Quail",
    "Scaly-breasted Munia",
    "Scaly-naped Pigeon",
    "Scarlet Ibis",
    "Scarlet Tanager",
    "Scissor-tailed Flycatcher",
    "Scott's Oriole",
    "Scripps's Murrelet",
    "Seaside Sparrow",
    "Sedge Warbler",
    "Sedge Wren",
    "Semipalmated Plover",
    "Semipalmated Sandpiper",
    "Sharp-shinned Hawk",
    "Sharp-tailed Grouse",
    "Sharp-tailed Sandpiper",
    "Shiny Cowbird",
    "Short-billed Dowitcher",
    "Short-billed Gull",
    "Short-eared Owl",
    "Short-tailed Albatross",
    "Short-tailed Hawk",
    "Short-tailed Shearwater",
    "Siberian Accentor",
    "Siberian Blue Robin",
    "Siberian Rubythroat",
    "Sinaloa Wren",
    "Slate-throated Redstart",
    "Slaty-backed Gull",
    "Slender-billed Curlew",
    "Small-billed Elaenia",
    "Smew",
    "Smith's Longspur",
    "Smooth-billed Ani",
    "Snail Kite",
    "Snow Bunting",
    "Snow Goose",
    "Snowy Egret",
    "Snowy Owl",
    "Snowy Plover",
    "Social Flycatcher",
    "Solitary Sandpiper",
    "Solitary Snipe",
    "Song Sparrow",
    "Song Thrush",
    "Sooty Grouse",
    "Sooty Shearwater",
    "Sooty Tern",
    "Sora",
    "South Polar Skua",
    "Southern Martin",
    "Spectacled Eider",
    "Spoon-billed Sandpiper",
    "Spot-breasted Oriole",
    "Spotted Dove",
    "Spotted Flycatcher",
    "Spotted Owl",
    "Spotted Rail",
    "Spotted Redshank",
    "Spotted Sandpiper",
    "Spotted Towhee",
    "Sprague's Pipit",
    "Spruce Grouse",
    "Stejneger's Petrel",
    "Stejneger's Scoter",
    "Steller's Eider",
    "Steller's Jay",
    "Steller's Sea-Eagle",
    "Stilt Sandpiper",
    "Stonechat",
    "Streak-backed Oriole",
    "Streaked Shearwater",
    "Stygian Owl",
    "Sulphur-bellied Flycatcher",
    "Summer Tanager",
    "Sungrebe",
    "Surf Scoter",
    "Surfbird",
    "Swainson's Hawk",
    "Swainson's Thrush",
    "Swainson's Warbler",
    "Swallow-tailed Gull",
    "Swallow-tailed Kite",
    "Swamp Sparrow",
    "Swinhoe's Storm-Petrel",
    "Tahiti Petrel",
    "Taiga Bean-Goose",
    "Taiga Flycatcher",
    "Tamaulipas Crow",
    "Tawny-shouldered Blackbird",
    "Temminck's Stint",
    "Tennessee Warbler",
    "Terek Sandpiper",
    "Thick-billed Kingbird",
    "Thick-billed Longspur",
    "Thick-billed Murre",
    "Thick-billed Parrot",
    "Thick-billed Vireo",
    "Thick-billed Warbler",
    "Townsend's Solitaire",
    "Townsend's Storm-Petrel",
    "Townsend's Warbler",
    "Tree Pipit",
    "Tree Swallow",
    "Tricolored Blackbird",
    "Tricolored Heron",
    "Tricolored Munia",
    "Trindade Petrel",
    "Tristram's Storm-Petrel",
    "Tropical Kingbird",
    "Tropical Parula",
    "Trumpeter Swan",
    "Tufted Duck",
    "Tufted Flycatcher",
    "Tufted Puffin",
    "Tufted Titmouse",
    "Tundra Bean-Goose",
    "Tundra Swan",
    "Turkey Vulture",
    "Ula-ai-hawane",
    "Upland Sandpiper",
    "Varied Bunting",
    "Varied Thrush",
    "Variegated Flycatcher",
    "Vaux's Swift",
    "Veery",
    "Verdin",
    "Vermilion Flycatcher",
    "Vesper Sparrow",
    "Violet-crowned Hummingbird",
    "Violet-green Swallow",
    "Virginia Rail",
    "Virginia's Warbler",
    "Wandering Albatross",
    "Wandering Tattler",
    "Warbling Vireo",
    "Warbling White-eye",
    "Wedge-rumped Storm-Petrel",
    "Wedge-tailed Shearwater",
    "Western Bluebird",
    "Western Grebe",
    "Western Gull",
    "Western Kingbird",
    "Western Meadowlark",
    "Western Reef-Heron",
    "Western Sandpiper",
    "Western Screech-Owl",
    "Western Spindalis",
    "Western Tanager",
    "Western Wood-Pewee",
    "Whimbrel",
    "Whiskered Auklet",
    "Whiskered Screech-Owl",
    "Whiskered Tern",
    "White Ibis",
    "White Tern",
    "White Wagtail",
    "White-breasted Nuthatch",
    "White-capped Albatross",
    "White-cheeked Pintail",
    "White-chinned Petrel",
    "White-collared Swift",
    "White-crested Elaenia",
    "White-crowned Pigeon",
    "White-crowned Sparrow",
    "White-eared Hummingbird",
    "White-eyed Vireo",
    "White-faced Ibis",
    "White-faced Storm-Petrel",
    "White-headed Woodpecker",
    "White-necked Petrel",
    "White-rumped Sandpiper",
    "White-rumped Shama",
    "White-tailed Eagle",
    "White-tailed Hawk",
    "White-tailed Kite",
    "White-tailed Ptarmigan",
    "White-tailed Tropicbird",
    "White-throated Needletail",
    "White-throated Sparrow",
    "White-throated Swift",
    "White-throated Thrush",
    "White-tipped Dove",
    "White-winged Crossbill",
    "White-winged Dove",
    "White-winged Parakeet",
    "White-winged Scoter",
    "White-winged Tern",
    "Whooper Swan",
    "Whooping Crane",
    "Wild Turkey",
    "Willet",
    "Williamson's Sapsucker",
    "Willow Flycatcher",
    "Willow Ptarmigan",
    "Willow Warbler",
    "Wilson's Phalarope",
    "Wilson's Plover",
    "Wilson's Snipe",
    "Wilson's Storm-Petrel",
    "Wilson's Warbler",
    "Winter Wren",
    "Wood Duck",
    "Wood Sandpiper",
    "Wood Stork",
    "Wood Thrush",
    "Wood Warbler",
    "Woodhouse's Scrub-Jay",
    "Worm-eating Warbler",
    "Worthen's Sparrow",
    "Wrentit",
    "Xantus's Hummingbird",
    "Yellow Bittern",
    "Yellow Grosbeak",
    "Yellow Rail",
    "Yellow Warbler",
    "Yellow-bellied Flycatcher",
    "Yellow-bellied Sapsucker",
    "Yellow-billed Cardinal",
    "Yellow-billed Cuckoo",
    "Yellow-billed Loon",
    "Yellow-billed Magpie",
    "Yellow-breasted Bunting",
    "Yellow-breasted Chat",
    "Yellow-browed Bunting",
    "Yellow-browed Warbler",
    "Yellow-chevroned Parakeet",
    "Yellow-crowned Night-Heron",
    "Yellow-eyed Junco",
    "Yellow-faced Grassquit",
    "Yellow-footed Gull",
    "Yellow-fronted Canary",
    "Yellow-green Vireo",
    "Yellow-headed Blackbird",
    "Yellow-legged Gull",
    "Yellow-nosed Albatross",
    "Yellow-rumped Warbler",
    "Yellow-throated Bunting",
    "Yellow-throated Vireo",
    "Yellow-throated Warbler",
    "Yucatan Vireo",
    "Zebra Dove",
    "Zenaida Dove",
    "Zino's Petrel",
    "Zone-tailed Hawk"
];

let randomNumber = Math.floor(Math.random() * birdCodes.length);
let answerCode = birdCodes[randomNumber];
let answerName = birdNames[randomNumber];
let answerNameClean = answerName.replace('\'','').toLowerCase()

const answerCodeDisp = document.querySelector(".answerCodeDisp");
const previousGuesses = document.querySelector(".previousGuesses");
const guesses = document.querySelector(".guesses");
const lastResult = document.querySelector(".lastResult");
const guessSubmit = document.querySelector(".guessSubmit");
const guessField = document.querySelector(".guessField");
let guessCount = 1;
let resetButton;
let giveUpButton;

guesses.style.whiteSpace = "pre";

answerCodeDisp.textContent = 'Code: ' + answerCode;

function checkGuess() {
    const userGuess = guessField.value;
    const userGuessClean = userGuess.replace('\'', '').toLowerCase()
    if (guessCount == 1) {
        previousGuesses.textContent = 'Previous guesses:';
    }

    if (userGuess.length > 0)
    guesses.textContent = userGuess + '\n' + guesses.textContent;

    if (userGuessClean == answerNameClean) {
        lastResult.textContent = answerName + ' is correct!';
        lastResult.style.color = 'green';
        setGameOver();
    } else {
        lastResult.textContent = 'WRONG!';
        lastResult.style.color = 'red';
    }

    if (guessCount == 1) {
        giveUpButton = document.createElement('button');
        giveUpButton.textContent = 'Give up';
        document.getElementById("guessForm").appendChild(giveUpButton);
        giveUpButton.addEventListener('click', giveUp);
    }

    guessCount++;
    guessField.value = '';
    guessField.focus();

}

guessSubmit.addEventListener('click', checkGuess);

function setGameOver() {
    guessField.disabled = true;
    guessSubmit.disabled = true;
    resetButton = document.createElement('button');
    resetButton.textContent = 'Start new game';
    document.getElementById("guessForm").appendChild(resetButton);
    resetButton.addEventListener('click', resetGame);
}

function giveUp() {
    setGameOver();
    let giveUpArticle = 'a '
    if (answerName.match('^[aieouAIEOU].*')) {
        giveUpArticle = 'an '
    }
    giveUpButton.parentNode.removeChild(giveUpButton);
    lastResult.textContent = 'Wow, fine. Just so you know, ' + giveUpArticle + answerName + ' is dead because of you. Great job.'
}

function resetGame() {
    guessCount = 1;
    const resetParas = document.querySelectorAll('.resultParas p');
    for (const resetPara of resetParas) {
        resetPara.textContent = '';
    }

    resetButton.parentNode.removeChild(resetButton);
    guessField.disabled = false;
    guessSubmit.disabled = false;
    guessField.value = '';
    guessField.focus();
    lastResult.style.color = 'black';
    randomNumber = Math.floor(Math.random() * birdCodes.length);
    answerCode = birdCodes[randomNumber];
    answerName = birdNames[randomNumber];
    answerCodeDisp.textContent = 'Code: ' + answerCode;
}