const birdCodes = ["BBWD",
    "WIWD",
    "FUWD",
    "TABG",
    "PFGO",
    "GWFG",
    "LWFG",
    "TWFG",
    "EMGO",
    "LSGO",
    "BLGO",
    "SBGI",
    "BGSG",
    "GSGO",
    "SRGH",
    "ROGO",
    "ATBR",
    "BABI",
    "BLBR",
    "BRNG",
    "ACGO",
    "CACG",
    "LCGO",
    "SCGO",
    "CAGO",
    "HAGO",
    "OHGO",
    "MUSW",
    "TRUS",
    "WHSW",
    "BESW",
    "WHOS",
    "MUDU",
    "WODU",
    "GADW",
    "FATE",
    "EUWI",
    "AMWI",
    "PBDU",
    "ABDU",
    "ABDX",
    "MBDX",
    "MBDH",
    "MALX",
    "MALL",
    "MODU",
    "MEDU",
    "HAWD",
    "LADU",
    "MHDH",
    "BWTE",
    "CITE",
    "NSHO",
    "WHIP",
    "NOPI",
    "GARG",
    "BATE",
    "EGWT",
    "AGWT",
    "UNTE",
    "CANV",
    "REDH",
    "CPOC",
    "RNDU",
    "TUDU",
    "GRSC",
    "LESC",
    "STEI",
    "SPEI",
    "KIEI",
    "COEI",
    "HARD",
    "SUSC",
    "WWSC",
    "BLSC",
    "LTDU",
    "BUFF",
    "COGO",
    "BAGO",
    "HOME",
    "COME",
    "RBME",
    "MADU",
    "RUDU",
    "OHDU",
    "MIME",
    "RTLO",
    "ARLO",
    "PALO",
    "COLO",
    "YBLO",
    "LEGR",
    "PBGR",
    "HOGR",
    "RNGR",
    "EAGR",
    "WEGR",
    "WCGR",
    "CLGR",
    "AMFL",
    "KIPE",
    "EMPE",
    "GEPE",
    "ADPE",
    "CHPE",
    "VIPE",
    "ROCP",
    "ROYP",
    "MACP",
    "FAPE",
    "AFPE",
    "MAGP",
    "HUPE",
    "GALP",
    "YNAL",
    "SHAL",
    "BBAL",
    "LMSA",
    "GHAL",
    "BUAL",
    "HYAL",
    "SGPE",
    "NGPE",
    "WAAL",
    "LAAL",
    "BFAL",
    "WAVA",
    "STAL",
    "ROAL",
    "SOAL",
    "NOFU",
    "SOFU",
    "ANPE",
    "CAPE",
    "SNPE",
    "BLPE",
    "BBPR",
    "DOPR",
    "TBPR",
    "FAPR",
    "KEPE",
    "MUPE",
    "MOPE",
    "BCPE",
    "JFPE",
    "TRPE",
    "PHPE",
    "HAPE",
    "BOPE",
    "BWPE",
    "COPE",
    "STPE",
    "TAPE",
    "BUPE",
    "WCPE",
    "STRS",
    "COSH",
    "PFSH",
    "FFSH",
    "GRSH",
    "WTSH",
    "BULS",
    "SOSH",
    "SHOS",
    "CHSH",
    "MASH",
    "NESH",
    "TOSH",
    "BVSH",
    "AUSH",
    "TRSH",
    "LISH",
    "WISP",
    "GBSP",
    "WFSP",
    "WHSP",
    "FTSP",
    "LHSP",
    "ASSP",
    "BANP",
    "WRSP",
    "BLSP",
    "TRSP",
    "LTSP",
    "WTTR",
    "RBTR",
    "RTTR",
    "WOST",
    "MAFR",
    "GRFR",
    "LEFR",
    "MABO",
    "NABO",
    "BFBO",
    "BRBO",
    "RFBO",
    "NOGA",
    "BRAC",
    "NECO",
    "DCCO",
    "GRCO",
    "RFCO",
    "PECO",
    "GUCO",
    "BECO",
    "ANHI",
    "AWPE",
    "BRPE",
    "AMBI",
    "YEBI",
    "LEBI",
    "GWHE",
    "GBHE",
    "GREG",
    "PRHE",
    "SNEG",
    "LBHE",
    "TRHE",
    "REEG",
    "CAEG",
    "GRHE",
    "BCNH",
    "YCNH",
    "WHIB",
    "SCIB",
    "GLIB",
    "WFIB",
    "ROSP",
    "BLVU",
    "TUVU",
    "CALC",
    "OSPR",
    "HBKI",
    "STKI",
    "WTKI",
    "SNKI",
    "MIKI",
    "BAEA",
    "NOHA",
    "SSHA",
    "PSSH",
    "COHA",
    "NOGO",
    "CBHA",
    "HRSH",
    "ROHA",
    "RSHA",
    "BWHA",
    "PBWH",
    "GRHA",
    "STHA",
    "SWHA",
    "WTHA",
    "ZTHA",
    "HWHA",
    "RTHA",
    "HRLH",
    "FEHA",
    "RLHA",
    "GOEA",
    "YERA",
    "BLRA",
    "EBRA",
    "CBRA",
    "BBRA",
    "GURA",
    "CRRA",
    "LFRR",
    "YRRA",
    "CLRA",
    "KIRA",
    "VIRA",
    "SORA",
    "YBCR",
    "PUSW",
    "PUGA",
    "COGA",
    "HAGA",
    "MCMO",
    "HACO",
    "AMCO",
    "CARC",
    "LIMP",
    "SACR",
    "MSCR",
    "BWST",
    "WHCR",
    "BNST",
    "HAST",
    "AMAV",
    "AMOY",
    "BLOY",
    "NOLA",
    "BBPL",
    "EUGP",
    "AMGP",
    "PAGP",
    "LEGP",
    "LRSP",
    "SNPL",
    "WSPL",
    "WIPL",
    "CRPL",
    "SEPL",
    "PIPL",
    "KILL",
    "MOPL",
    "EUDO",
    "SNSH",
    "LESH",
    "NOJA",
    "COSA",
    "SPSA",
    "SOSA",
    "GTTA",
    "WATA",
    "CGRE",
    "GRYE",
    "WILL",
    "LEYE",
    "MASA",
    "WOSA",
    "UPSA",
    "WHIM",
    "BTCU",
    "LBCU",
    "BLAG",
    "HUGO",
    "BARG",
    "MAGO",
    "RUTU",
    "BLTU",
    "REKN",
    "RRKN",
    "SURF",
    "RUFF",
    "SHAS",
    "STSA",
    "CUSA",
    "LTST",
    "SPOS",
    "RNST",
    "SAND",
    "DUNL",
    "ROSA",
    "PUSA",
    "BASA",
    "LIST",
    "LESA",
    "WRSA",
    "BBSA",
    "PESA",
    "SESA",
    "WESA",
    "SBDO",
    "LBDO",
    "COSN",
    "WISN",
    "PTSN",
    "SWSN",
    "EUWO",
    "AMWO",
    "WIPH",
    "RNPH",
    "REPH",
    "GRSK",
    "SPSK",
    "BRSK",
    "HYSK",
    "POJA",
    "PAJA",
    "LTJA",
    "DOVE",
    "COMU",
    "TBMU",
    "RAZO",
    "BLGU",
    "PIGU",
    "LBMU",
    "AMMU",
    "MAMU",
    "KIMU",
    "XAMU",
    "SCMU",
    "GUMU",
    "CRMU",
    "ANMU",
    "CAAU",
    "PAAU",
    "LEAU",
    "WHAU",
    "CRAU",
    "RHAU",
    "ATPU",
    "HOPU",
    "TUPU",
    "BLKI",
    "RLKI",
    "IVGU",
    "SAGU",
    "BOGU",
    "BHGU",
    "LIGU",
    "ROGU",
    "MAGU",
    "LAGU",
    "FRGU",
    "BTGU",
    "HEEG",
    "MEGU",
    "RBGU",
    "WEGU",
    "YFGU",
    "CAGU",
    "HERG",
    "THGU",
    "ICGU",
    "LBBG",
    "SBGU",
    "GWGU",
    "GLGU",
    "GBBG",
    "SBBG",
    "HYGU",
    "UNGU",
    "BRNO",
    "BLNO",
    "BGNO",
    "WHTE",
    "SOTE",
    "GRAT",
    "BRTE",
    "ALTE",
    "LITE",
    "LETE",
    "ILTE",
    "CLTE",
    "GBTE",
    "CATE",
    "BLTE",
    "WWTE",
    "WHIT",
    "ROST",
    "BNTE",
    "HCRT",
    "COTE",
    "ARTE",
    "ANTE",
    "KETE",
    "FOTE",
    "ROYT",
    "CRTE",
    "SATE",
    "CAYT",
    "ELTE",
    "HYTE",
    "BLSK",
    "SNPI",
    "WCPI",
    "RBPI",
    "PLPI",
    "PRPP",
    "BTPI",
    "PHTD",
    "AFCD",
    "ECDO",
    "SPDO",
    "ZEBD",
    "INDO",
    "COGD",
    "RUGD",
    "RUQD",
    "WTGD",
    "SHGD",
    "MCFD",
    "PCFD",
    "MAFD",
    "PAPI",
    "KWQD",
    "BRQD",
    "WTDO",
    "CADO",
    "WWDO",
    "ZEND",
    "EADO",
    "MODO",
    "YBCU",
    "WYBC",
    "MACU",
    "BBCU",
    "PRLC",
    "LTCU",
    "GRRO",
    "SBAN",
    "GBAN",
    "BNOW",
    "AFOW",
    "FLOW",
    "WESO",
    "EASO",
    "WHSO",
    "PRSO",
    "GHOW",
    "SNOW",
    "NHOW",
    "NOPO",
    "FEPO",
    "ELOW",
    "BUOW",
    "SPOW",
    "SBOH",
    "CSOW",
    "NSOW",
    "MSOW",
    "BDOW",
    "GGOW",
    "LEOW",
    "SEOW",
    "BOOW",
    "NSWO",
    "LENI",
    "CONI",
    "ANNI",
    "COPA",
    "COPO",
    "CWWI",
    "BCNI",
    "EWPW",
    "MWPW",
    "PRNI",
    "BLSW",
    "CHSW",
    "VASW",
    "STSW",
    "WRSW",
    "GUSW",
    "MGSW",
    "WTSW",
    "GVIO",
    "GREM",
    "ANMA",
    "GRMA",
    "JAMA",
    "GTCA",
    "MAHU",
    "PCST",
    "BLUH",
    "BAWO",
    "LUHU",
    "RTHU",
    "BCHU",
    "ANHU",
    "COHU",
    "BUHU",
    "BTLH",
    "RUHU",
    "ALHU",
    "HYHU",
    "UNHU",
    "CAHU",
    "PREM",
    "BBLH",
    "ACHU",
    "BEHU",
    "RUFH",
    "BUFH",
    "VCHU",
    "STTL",
    "WEHU",
    "ELTR",
    "EAQU",
    "JATO",
    "PRTO",
    "COLK",
    "MICK",
    "GMKI",
    "RIKI",
    "BEKI",
    "GKIN",
    "LEWO",
    "PRWO",
    "RHWO",
    "ACWO",
    "GIWO",
    "GFWO",
    "RBWO",
    "WIWO",
    "WISA",
    "YBSA",
    "RNSA",
    "RBSA",
    "HYSA",
    "LBWO",
    "NUWO",
    "DOWO",
    "HAWO",
    "ARWO",
    "RCWO",
    "WHWO",
    "ATTW",
    "BBWO",
    "YSFL",
    "FLIN",
    "RSFL",
    "GIFL",
    "PIWO",
    "IBWO",
    "CRCA",
    "ACCA",
    "EUKE",
    "AMKE",
    "MERL",
    "APFA",
    "GYRF",
    "PEFA",
    "PRFA",
    "BCLO",
    "MOPA",
    "BHPA",
    "OFPA",
    "BTPA",
    "HPKT",
    "TBPA",
    "CHCO",
    "HPRT",
    "PRPA",
    "RCPA",
    "OWAM",
    "NBTY",
    "JAEL",
    "GREL",
    "CAEL",
    "YBEL",
    "GAEL",
    "OSFL",
    "GRPE",
    "WEWP",
    "EAWP",
    "CUPE",
    "JAPE",
    "HIPE",
    "LAPE",
    "YBFL",
    "ACFL",
    "ALFL",
    "TRFL",
    "WIFL",
    "SWFL",
    "LEFL",
    "HAFL",
    "GRFL",
    "DUFL",
    "PSFL",
    "WEFL",
    "COFL",
    "BBFL",
    "UNEM",
    "BLPH",
    "EAPH",
    "SAPH",
    "VEFL",
    "SAFL",
    "DCFL",
    "ATFL",
    "NUFL",
    "GCFL",
    "BCFL",
    "LSFL",
    "STOF",
    "PRFL",
    "LESF",
    "GKIS",
    "SBFL",
    "TRKI",
    "COKI",
    "CAKI",
    "TBKI",
    "WEKI",
    "EAKI",
    "GRAK",
    "LOKI",
    "STFL",
    "FTFL",
    "RTBE",
    "CAHO",
    "WAHO",
    "MIHO",
    "BRSH",
    "LOSH",
    "SLSH",
    "NSHR",
    "WEVI",
    "TBVI",
    "JAVI",
    "PRVI",
    "BEVI",
    "LBVI",
    "BCVI",
    "GRVI",
    "YTVI",
    "PLVI",
    "CAVI",
    "BHVI",
    "SOVI",
    "HUVI",
    "WAVI",
    "PHVI",
    "REVI",
    "YGVI",
    "BWVI",
    "BLDR",
    "RUFA",
    "FISH",
    "TIMO",
    "CAJA",
    "BRJA",
    "GREJ",
    "PIJA",
    "STJA",
    "BLJA",
    "FLSJ",
    "CASJ",
    "ISSJ",
    "WESJ",
    "WOSJ",
    "MEJA",
    "CLNU",
    "BBMA",
    "YBMA",
    "MARC",
    "AMCR",
    "NOCR",
    "WNCR",
    "JACR",
    "TACR",
    "FICR",
    "HCRO",
    "CHRA",
    "CORA",
    "KAEL",
    "OAEL",
    "HAEL",
    "EUSK",
    "HOLA",
    "SHLA",
    "PUMA",
    "CAMA",
    "GBMA",
    "TRES",
    "VGSW",
    "BAHS",
    "NRWS",
    "BANS",
    "CLSW",
    "CASW",
    "BARS",
    "CACH",
    "BCCH",
    "MOCH",
    "MECH",
    "CBCH",
    "BOCH",
    "GHCH",
    "HYCH",
    "VATI",
    "BRTI",
    "OATI",
    "JUTI",
    "TUTI",
    "PLTI",
    "BCTI",
    "VERD",
    "BUSH",
    "RBNU",
    "WBNU",
    "PYNU",
    "BHNU",
    "BRCR",
    "ROWR",
    "CANW",
    "HOWR",
    "SHWR",
    "PAWR",
    "WIWR",
    "SEWR",
    "MAWR",
    "CARW",
    "BEWR",
    "CACW",
    "BGGN",
    "CAGN",
    "BACG",
    "BTGN",
    "BCGN",
    "AMDI",
    "RVBU",
    "RWBU",
    "GCKI",
    "RCKI",
    "JABW",
    "WOWA",
    "DUWA",
    "ARWA",
    "WREN",
    "JAWE",
    "GNLA",
    "HWAM",
    "RBLE",
    "MILL",
    "NIRW",
    "MIGW",
    "GOWE",
    "ROWE",
    "BRWE",
    "LANW",
    "GSFL",
    "DSFL",
    "WRSH",
    "SIRU",
    "BLUE",
    "RFBL",
    "TAFL",
    "NOWH",
    "EABL",
    "WEBL",
    "MOBL",
    "HYBL",
    "TOSO",
    "RTSO",
    "KAMA",
    "OLOM",
    "OMAO",
    "PUAI",
    "OBNT",
    "VEER",
    "GCTH",
    "BITH",
    "GCBT",
    "SWTH",
    "HETH",
    "WOTH",
    "EYTH",
    "DUTH",
    "FIEL",
    "REDW",
    "CCTH",
    "WETH",
    "RBRO",
    "AMRO",
    "WCTH",
    "RLTH",
    "VATH",
    "AZTH",
    "GRCA",
    "PETH",
    "BRTR",
    "CBTH",
    "BRTH",
    "LBTH",
    "BETH",
    "CATH",
    "LCTH",
    "CRTH",
    "SATH",
    "BAMO",
    "TRMO",
    "NOMO",
    "BLMO",
    "MIST",
    "POST",
    "SAST",
    "EUST",
    "CRMY",
    "JAMY",
    "JUMY",
    "COMY",
    "HIMY",
    "SIAC",
    "EYWA",
    "GRAW",
    "WHWA",
    "BWAG",
    "OBPI",
    "PEPI",
    "RTPI",
    "AMPI",
    "SPPI",
    "BOWA",
    "CEDW",
    "KAOO",
    "BIOO",
    "PHAI",
    "OLWA",
    "LALO",
    "CCLO",
    "SMLO",
    "MCLO",
    "SNBU",
    "MKBU",
    "OVEN",
    "WEWA",
    "LOWA",
    "NOWA",
    "GWWA",
    "BWWA",
    "BRWA",
    "LAWA",
    "GBWH",
    "BAWW",
    "PROW",
    "SWWA",
    "TEWA",
    "OCWA",
    "COLW",
    "LUWA",
    "NAWA",
    "VIWA",
    "CONW",
    "GCYE",
    "MGWA",
    "MOWA",
    "KEWA",
    "BAYE",
    "COYE",
    "EWWA",
    "ARRW",
    "HOWA",
    "AMRE",
    "KIWA",
    "CMWA",
    "CERW",
    "NOPA",
    "TRPA",
    "MAWA",
    "BBWA",
    "BLBW",
    "YEWA",
    "CSWA",
    "BLPW",
    "BTBW",
    "WPWA",
    "YPWA",
    "OLIW",
    "PIWA",
    "MYWA",
    "UYRW",
    "AUWA",
    "YTWA",
    "SUWA",
    "PRAW",
    "ADWA",
    "BARW",
    "SLWA",
    "GRWA",
    "BTYW",
    "TOWA",
    "THWH",
    "HEWA",
    "GCWA",
    "BTNW",
    "FTWA",
    "RCWA",
    "GOLW",
    "CAWA",
    "WIWA",
    "RFWA",
    "PARE",
    "SLAR",
    "YBCH",
    "HYWA",
    "BANA",
    "RCCA",
    "YBCA",
    "PRTA",
    "WESP",
    "HISP",
    "PRSP",
    "JAMS",
    "BBGR",
    "WCSE",
    "YBSE",
    "CUGR",
    "YFGR",
    "BFGR",
    "YSGR",
    "PUEB",
    "GABU",
    "LESB",
    "ORAN",
    "SAFI",
    "OLSP",
    "GTTO",
    "SPTO",
    "EATO",
    "URST",
    "HYTO",
    "ICTO",
    "RCSP",
    "CANT",
    "CALT",
    "ABTO",
    "RWSP",
    "BOSP",
    "CASP",
    "BACS",
    "ATSP",
    "CHSP",
    "CCSP",
    "BRSP",
    "FISP",
    "WOSP",
    "BCSP",
    "VESP",
    "LASP",
    "FSSP",
    "BTSP",
    "SBSP",
    "USSP",
    "SCBS",
    "BESP",
    "LARB",
    "SAVS",
    "IPSP",
    "BSSP",
    "LBSP",
    "GRSP",
    "FGSP",
    "BAIS",
    "HESP",
    "LCSP",
    "NESP",
    "SALS",
    "STSP",
    "SESP",
    "DSSP",
    "CSSS",
    "FOSP",
    "SOSP",
    "LISP",
    "SWSP",
    "RUFS",
    "WTSP",
    "HASP",
    "WCSP",
    "EWCS",
    "MWCS",
    "PSWS",
    "GWCS",
    "NWCS",
    "GCSP",
    "WWJU",
    "ZSHY",
    "SCJU",
    "ORJU",
    "UDEJ",
    "GHJU",
    "YEJU",
    "LIBU",
    "RUBU",
    "GRBU",
    "PALB",
    "REBU",
    "HETA",
    "SUTA",
    "SCTA",
    "WETA",
    "FCTA",
    "NOCA",
    "PYRR",
    "YEGR",
    "RBGR",
    "BHGR",
    "BLBU",
    "BLGR",
    "LAZB",
    "ILBH",
    "INBU",
    "VABU",
    "PABU",
    "DICK",
    "BOBO",
    "RWBL",
    "TRBL",
    "TSBL",
    "YSBL",
    "EAME",
    "WEME",
    "YHBL",
    "RUBL",
    "BRBL",
    "COGR",
    "BTGR",
    "GTGR",
    "GAGR",
    "SHCO",
    "BROC",
    "BHCO",
    "BAHO",
    "CUOR",
    "HIOR",
    "PROR",
    "BVOR",
    "BCOR",
    "OROR",
    "HOOR",
    "VETR",
    "STRO",
    "BUOR",
    "BBOH",
    "JAOR",
    "SPOO",
    "ALOR",
    "AUOR",
    "BAOR",
    "SCOR",
    "COCH",
    "BRAM",
    "JAEU",
    "ANEU",
    "GCRF",
    "BLRF",
    "BCRF",
    "PIGR",
    "EUBU",
    "LAFI",
    "NIFI",
    "OU",
    "PALI",
    "MAPA",
    "HAAM",
    "OAAM",
    "KAAM",
    "OAAK",
    "NUKU",
    "AKIP",
    "ANIA",
    "AKIK",
    "OAAL",
    "KAKA",
    "MAAL",
    "HCRE",
    "AKEK",
    "AKEP",
    "IIWI",
    "AKOH",
    "APAP",
    "POUL",
    "CORO",
    "HOFI",
    "PUFI",
    "CAFI",
    "RECR",
    "CACR",
    "WWCR",
    "CORE",
    "HORE",
    "UNRE",
    "PISI",
    "RESI",
    "LEGO",
    "LAGO",
    "AMGO",
    "EUGO",
    "ORGR",
    "YFCA",
    "COCA",
    "EVGR",
    "HAWF",
    "HOSP",
    "ETSP",
    "YCBI",
    "NRBI",
    "RCCO",
    "LAVW",
    "ORAW",
    "BRWX",
    "COMW",
    "REAV",
    "BRMA",
    "AFSI",
    "JAVS",
    "SBMU",
    "TRMU",
    "PTWH"];

const birdNames = [
    "Black-bellied Whistling-Duck",
    "West Indian Whistling-Duck",
    "Fulvous Whistling-Duck",
    "Taiga Bean-Goose",
    "Pink-footed Goose",
    "Greater White-fronted Goose",
    "Lesser White-fronted Goose",
    "Tule White-fronted Goose",
    "Emperor Goose",
    "Lesser Snow Goose",
    "Blue Goose",
    "Snow X Blue Goose Intergrade",
    "Blue Greater Snow Goose",
    "Greater Snow Goose",
    "Snow X Ross's Goose Hybrid",
    "Ross's Goose",
    "Atlantic Brant",
    "Black X Atlantic Brant Intergrade",
    "Black Brant",
    "Barnacle Goose",
    "Aleutian Canada Goose",
    "Cackling Goose",
    "Large Canada Goose",
    "Small Canada Goose",
    "Canada Goose",
    "Hawaiian Goose",
    "Other Hybrid Goose",
    "Mute Swan",
    "Trumpeter Swan",
    "Whistling Swan",
    "Bewick's Swan",
    "Whooper Swan",
    "Muscovy Duck",
    "Wood Duck",
    "Gadwall",
    "Falcated Teal",
    "Eurasian Wigeon",
    "American Wigeon",
    "Pacific Black Duck",
    "American Black Duck",
    "American Black Duck Dominant X Mallard Hybrid",
    "Mallard X American Black Duck Intermediate",
    "Mallard X American Black Duck Hybrid",
    "Mallard Dominant X American Black Duck Hybrid",
    "Mallard",
    "Mottled Duck",
    "Mexican Duck",
    "Hawaiian Duck",
    "Laysan Duck",
    "Mallard X Hawaiian Duck Hybrid",
    "Blue-winged Teal",
    "Cinnamon Teal",
    "Northern Shoveler",
    "White-cheeked Pintail",
    "Northern Pintail",
    "Garganey",
    "Baikal Teal",
    "European Green-winged Teal",
    "Green-winged Teal",
    "Unidentified Teal",
    "Canvasback",
    "Redhead",
    "Common Pochard",
    "Ring-necked Duck",
    "Tufted Duck",
    "Greater Scaup",
    "Lesser Scaup",
    "Steller's Eider",
    "Spectacled Eider",
    "King Eider",
    "Common Eider",
    "Harlequin Duck",
    "Surf Scoter",
    "White-winged Scoter",
    "Black Scoter",
    "Long-tailed Duck",
    "Bufflehead",
    "Common Goldeneye",
    "Barrow's Goldeneye",
    "Hooded Merganser",
    "Common Merganser",
    "Red-breasted Merganser",
    "Masked Duck",
    "Ruddy Duck",
    "Other Hybrid Duck",
    "Micronesian Megapode",
    "Red-throated Loon",
    "Arctic Loon",
    "Pacific Loon",
    "Common Loon",
    "Yellow-billed Loon",
    "Least Grebe",
    "Pied-billed Grebe",
    "Horned Grebe",
    "Red-necked Grebe",
    "Eared Grebe",
    "Western Grebe",
    "Western/Clark's Grebe",
    "Clark's Grebe",
    "American Flamingo",
    "King Penguin",
    "Emperor Penguin",
    "Gentoo Penguin",
    "Adelie Penguin",
    "Chinstrap Penguin",
    "Victoria Penguin",
    "Rockhopper Penguin",
    "Royal Penguin",
    "Macaroni Penguin",
    "Fairy Penguin",
    "African Penguin",
    "Magellanic Penguin",
    "Humboldt Penguin",
    "Galapagos Penguin",
    "Yellow-nosed Albatross",
    "Shy Albatross",
    "Black-browed Albatross",
    "Light-mantled Albatross",
    "Gray-headed Albatross",
    "Buller's Albatross",
    "Hybrid Albatross",
    "Southern Giant Petrel",
    "Northern Giant Petrel",
    "Wandering Albatross",
    "Laysan Albatross",
    "Black-footed Albatross",
    "Waved Albatross",
    "Short-tailed Albatross",
    "Royal Albatross",
    "Sooty Albatross",
    "Northern Fulmar",
    "Southern Fulmar",
    "Antarctic Petrel",
    "Cape Petrel",
    "Snow Petrel",
    "Blue Petrel",
    "Broad-billed Prion",
    "Dove Prion",
    "Thin-billed Prion",
    "Fairy Prion",
    "Kerguelen Petrel",
    "Murphy's Petrel",
    "Mottled Petrel",
    "Black-capped Petrel",
    "Juan Fernandez Petrel",
    "Trindade Petrel",
    "Phoenix Petrel",
    "Hawaiian Petrel",
    "Bonin Petrel",
    "Black-winged Petrel",
    "Cook's Petrel",
    "Stejneger's Petrel",
    "Tahiti Petrel",
    "Bulwer's Petrel",
    "White-chinned Petrel",
    "Streaked Shearwater",
    "Cory's Shearwater",
    "Pink-footed Shearwater",
    "Flesh-footed Shearwater",
    "Great Shearwater",
    "Wedge-tailed Shearwater",
    "Buller's Shearwater",
    "Sooty Shearwater",
    "Short-tailed Shearwater",
    "Christmas Shearwater",
    "Manx Shearwater",
    "Newell's Shearwater",
    "Townsend's Shearwater",
    "Black-vented Shearwater",
    "Audubon's Shearwater",
    "Tropical Shearwater",
    "Little Shearwater",
    "Wilson's Storm-Petrel",
    "Gray-backed Storm-Petrel",
    "White-faced Storm-Petrel",
    "White-throated Storm-Petrel",
    "Fork-tailed Storm-Petrel",
    "Leach's Storm-Petrel",
    "Ashy Storm-Petrel",
    "Band-rumped Storm-Petrel",
    "Wedge-rumped Storm-Petrel",
    "Black Storm-Petrel",
    "Tristram's Storm-Petrel",
    "Least Storm-Petrel",
    "White-tailed Tropicbird",
    "Red-billed Tropicbird",
    "Red-tailed Tropicbird",
    "Wood Stork",
    "Magnificent Frigatebird",
    "Great Frigatebird",
    "Lesser Frigatebird",
    "Masked Booby",
    "Nazca Booby",
    "Blue-footed Booby",
    "Brown Booby",
    "Red-footed Booby",
    "Northern Gannet",
    "Brandt's Cormorant",
    "Neotropic Cormorant",
    "Double-crested Cormorant",
    "Great Cormorant",
    "Red-faced Cormorant",
    "Pelagic Cormorant",
    "Guanay Cormorant",
    "Blue-eyed Cormorant",
    "Anhinga",
    "American White Pelican",
    "Brown Pelican",
    "American Bittern",
    "Yellow Bittern",
    "Least Bittern",
    "Great White Heron",
    "Great Blue Heron",
    "Great Egret",
    "Pacific Reef Heron",
    "Snowy Egret",
    "Little Blue Heron",
    "Tricolored Heron",
    "Reddish Egret",
    "Cattle Egret",
    "Green Heron",
    "Black-crowned Night-Heron",
    "Yellow-crowned Night-Heron",
    "White Ibis",
    "Scarlet Ibis",
    "Glossy Ibis",
    "White-faced Ibis",
    "Roseate Spoonbill",
    "Black Vulture",
    "Turkey Vulture",
    "California Condor",
    "Osprey",
    "Hook-billed Kite",
    "Swallow-tailed Kite",
    "White-tailed Kite",
    "Snail Kite",
    "Mississippi Kite",
    "Bald Eagle",
    "Northern Harrier",
    "Sharp-shinned Hawk",
    "Puerto Rican Sharp-shinned Hawk",
    "Cooper's Hawk",
    "Northern Goshawk",
    "Common Black Hawk",
    "Harris's Hawk",
    "Roadside Hawk",
    "Red-shouldered Hawk",
    "Broad-winged Hawk",
    "Puerto Rican Broad-winged Hawk",
    "Gray Hawk",
    "Short-tailed Hawk",
    "Swainson's Hawk",
    "White-tailed Hawk",
    "Zone-tailed Hawk",
    "Hawaiian Hawk",
    "Red-tailed Hawk",
    "Harlan's Hawk",
    "Ferruginous Hawk",
    "Rough-legged Hawk",
    "Golden Eagle",
    "Yellow Rail",
    "Black Rail",
    "Eastern Black Rail",
    "California Black Rail",
    "Buff-banded Rail",
    "Guam Rail",
    "California Ridgway's Rail",
    "Light-footed Ridgway's Rail",
    "Yuma Ridgway's Rail",
    "Clapper Rail",
    "King Rail",
    "Virginia Rail",
    "Sora",
    "Yellow-breasted Crake",
    "Purple Swamphen",
    "Purple Gallinule",
    "Common Gallinule",
    "Hawaiian Gallinule",
    "Mariana Common Moorhen",
    "Hawaiian Coot",
    "American Coot",
    "Caribbean Coot",
    "Limpkin",
    "Sandhill Crane",
    "Mississippi Sandhill Crane",
    "Black-winged Stilt",
    "Whooping Crane",
    "Black-necked Stilt",
    "Hawaiian Stilt",
    "American Avocet",
    "American Oystercatcher",
    "Black Oystercatcher",
    "Northern Lapwing",
    "Black-bellied Plover",
    "European Golden-Plover",
    "American Golden-Plover",
    "Pacific Golden-Plover",
    "Lesser Golden-Plover",
    "Lesser Sand-Plover",
    "Snowy Plover",
    "Western Snowy Plover",
    "Wilson's Plover",
    "Common Ringed Plover",
    "Semipalmated Plover",
    "Piping Plover",
    "Killdeer",
    "Mountain Plover",
    "Eurasian Dotterel",
    "Snowy Sheathbill",
    "Lesser Sheathbill",
    "Northern Jacana",
    "Common Sandpiper",
    "Spotted Sandpiper",
    "Solitary Sandpiper",
    "Gray-tailed Tattler",
    "Wandering Tattler",
    "Common Greenshank",
    "Greater Yellowlegs",
    "Willet",
    "Lesser Yellowlegs",
    "Marsh Sandpiper",
    "Wood Sandpiper",
    "Upland Sandpiper",
    "Whimbrel",
    "Bristle-thighed Curlew",
    "Long-billed Curlew",
    "Black-tailed Godwit",
    "Hudsonian Godwit",
    "Bar-tailed Godwit",
    "Marbled Godwit",
    "Ruddy Turnstone",
    "Black Turnstone",
    "Red Knot",
    "Rufa Red Knot",
    "Surfbird",
    "Ruff",
    "Sharp-tailed Sandpiper",
    "Stilt Sandpiper",
    "Curlew Sandpiper",
    "Long-toed Stint",
    "Spoon-billed Sandpiper",
    "Red-necked Stint",
    "Sanderling",
    "Dunlin",
    "Rock Sandpiper",
    "Purple Sandpiper",
    "Baird's Sandpiper",
    "Little Stint",
    "Least Sandpiper",
    "White-rumped Sandpiper",
    "Buff-breasted Sandpiper",
    "Pectoral Sandpiper",
    "Semipalmated Sandpiper",
    "Western Sandpiper",
    "Short-billed Dowitcher",
    "Long-billed Dowitcher",
    "Common Snipe",
    "Wilson's Snipe",
    "Pin-tailed Snipe",
    "Swinhoe's Snipe",
    "Eurasian Woodcock",
    "American Woodcock",
    "Wilson's Phalarope",
    "Red-necked Phalarope",
    "Red Phalarope",
    "Great Skua",
    "South Polar Skua",
    "Brown Skua",
    "Hybrid Skua",
    "Pomarine Jaeger",
    "Parasitic Jaeger",
    "Long-tailed Jaeger",
    "Dovekie",
    "Common Murre",
    "Thick-billed Murre",
    "Razorbill",
    "Black Guillemot",
    "Pigeon Guillemot",
    "Long-billed Murrelet",
    "Alaska Marbled Murrelet",
    "Marbled Murrelet",
    "Kittlitz's Murrelet",
    "Xantus's Murrelet",
    "Scripps's Murrelet",
    "Guadalupe Murrelet",
    "Craveri's Murrelet",
    "Ancient Murrelet",
    "Cassin's Auklet",
    "Parakeet Auklet",
    "Least Auklet",
    "Whiskered Auklet",
    "Crested Auklet",
    "Rhinoceros Auklet",
    "Atlantic Puffin",
    "Horned Puffin",
    "Tufted Puffin",
    "Black-legged Kittiwake",
    "Red-legged Kittiwake",
    "Ivory Gull",
    "Sabine's Gull",
    "Bonaparte's Gull",
    "Black-headed Gull",
    "Little Gull",
    "Ross's Gull",
    "Magellan Gull",
    "Laughing Gull",
    "Franklin's Gull",
    "Band-tailed Gull",
    "Heermann's Gull",
    "Mew Gull",
    "Ring-billed Gull",
    "Western Gull",
    "Yellow-footed Gull",
    "California Gull",
    "Herring Gull",
    "Thayer's Gull",
    "Iceland Gull",
    "Lesser Black-backed Gull",
    "Slaty-backed Gull",
    "Glaucous-winged Gull",
    "Glaucous Gull",
    "Great Black-backed Gull",
    "Southern Black-backed Gull",
    "Hybrid Gull",
    "Unidentified Gull",
    "Brown Noddy",
    "Black Noddy",
    "Blue-gray Noddy",
    "White Tern",
    "Sooty Tern",
    "Gray-backed Tern",
    "Bridled Tern",
    "Aleutian Tern",
    "Little Tern",
    "Least Tern",
    "Interior Least Tern",
    "California Least Tern",
    "Gull-billed Tern",
    "Caspian Tern",
    "Black Tern",
    "White-winged Tern",
    "Whiskered Tern",
    "Roseate Tern",
    "Black-naped Tern",
    "Common Tern X Roseate Tern Hybrid",
    "Common Tern",
    "Arctic Tern",
    "Antarctic Tern",
    "Kerguelen Tern",
    "Forster's Tern",
    "Royal Tern",
    "Crested Tern",
    "Sandwich Tern",
    "Cayenne Tern",
    "Elegant Tern",
    "Hybrid Tern",
    "Black Skimmer",
    "Scaly-naped Pigeon",
    "White-crowned Pigeon",
    "Red-billed Pigeon",
    "Plain Pigeon",
    "Puerto Rican Plain Pigeon",
    "Band-tailed Pigeon",
    "Philippine Turtle-Dove",
    "African Collared-Dove",
    "Eurasian Collared-Dove",
    "Spotted Dove",
    "Zebra Dove",
    "Inca Dove",
    "Common Ground-Dove",
    "Ruddy Ground-Dove",
    "Ruddy Quail-Dove",
    "White-throated Ground-Dove",
    "Shy Ground Dove",
    "Many-colored Fruit Dove",
    "Purple-capped Fruit Dove",
    "Mariana Fruit Dove",
    "Pacific Pigeon",
    "Key West Quail-Dove",
    "Bridled Quail-Dove",
    "White-tipped Dove",
    "Caribbean Dove",
    "White-winged Dove",
    "Zenaida Dove",
    "Eared Dove",
    "Mourning Dove",
    "Yellow-billed Cuckoo",
    "Western Yellow-billed Cuckoo",
    "Mangrove Cuckoo",
    "Black-billed Cuckoo",
    "Puerto Rican Lizard-Cuckoo",
    "Long-tailed Cuckoo",
    "Greater Roadrunner",
    "Smooth-billed Ani",
    "Groove-billed Ani",
    "Barn Owl",
    "Ashy-faced Owl",
    "Flammulated Owl",
    "Western Screech-Owl",
    "Eastern Screech-Owl",
    "Whiskered Screech-Owl",
    "Puerto Rican Screech-Owl",
    "Great Horned Owl",
    "Snowy Owl",
    "Northern Hawk Owl",
    "Northern Pygmy-Owl",
    "Ferruginous Pygmy-Owl",
    "Elf Owl",
    "Burrowing Owl",
    "Spotted Owl",
    "Spotted X Barred Owl Hybrid",
    "California Spotted Owl",
    "Northern Spotted Owl",
    "Mexican Spotted Owl",
    "Barred Owl",
    "Great Gray Owl",
    "Long-eared Owl",
    "Short-eared Owl",
    "Boreal Owl",
    "Northern Saw-whet Owl",
    "Lesser Nighthawk",
    "Common Nighthawk",
    "Antillean Nighthawk",
    "Common Pauraque",
    "Common Poorwill",
    "Chuck-will's-widow",
    "Buff-collared Nightjar",
    "Eastern Whip-poor-will",
    "Mexican Whip-poor-will",
    "Puerto Rican Nightjar",
    "Black Swift",
    "Chimney Swift",
    "Vaux's Swift",
    "Short-tailed Swift",
    "White-rumped Swiftlet",
    "Guam Swiftlet",
    "Mariana Gray Swiftlet",
    "White-throated Swift",
    "Green Violetear",
    "Green-breasted Mango",
    "Antillean Mango",
    "Green Mango",
    "Jamaican Mango",
    "Green-throated Carib",
    "Magnificent Hummingbird",
    "Plain-capped Starthroat",
    "Blue-throated Hummingbird",
    "Bahama Woodstar",
    "Lucifer Hummingbird",
    "Ruby-throated Hummingbird",
    "Black-chinned Hummingbird",
    "Anna's Hummingbird",
    "Costa's Hummingbird",
    "Bumblebee Hummingbird",
    "Broad-tailed Hummingbird",
    "Rufous Hummingbird",
    "Allen's Hummingbird",
    "Hybrid Hummingbird",
    "Unidentified Hummingbird",
    "Calliope Hummingbird",
    "Puerto Rican Emerald",
    "Broad-billed Hummingbird",
    "Antillean Crested Hummingbird",
    "Berylline Hummingbird",
    "Rufous-tailed Hummingbird",
    "Buff-bellied Hummingbird",
    "Violet-crowned Hummingbird",
    "Streamertail",
    "White-eared Hummingbird",
    "Elegant Trogon",
    "Eared Quetzal",
    "Jamaican Tody",
    "Puerto Rican Tody",
    "Collared Kingfisher",
    "Micronesian Kingfisher",
    "Guam Micronesian Kingfisher",
    "Ringed Kingfisher",
    "Belted Kingfisher",
    "Green Kingfisher",
    "Lewis's Woodpecker",
    "Puerto Rican Woodpecker",
    "Red-headed Woodpecker",
    "Acorn Woodpecker",
    "Gila Woodpecker",
    "Golden-fronted Woodpecker",
    "Red-bellied Woodpecker",
    "West Indian Woodpecker",
    "Williamson's Sapsucker",
    "Yellow-bellied Sapsucker",
    "Red-naped Sapsucker",
    "Red-breasted Sapsucker",
    "Hybrid Sapsucker",
    "Ladder-backed Woodpecker",
    "Nuttall's Woodpecker",
    "Downy Woodpecker",
    "Hairy Woodpecker",
    "Arizona Woodpecker",
    "Red-cockaded Woodpecker",
    "White-headed Woodpecker",
    "American Three-toed Woodpecker",
    "Black-backed Woodpecker",
    "Yellow-shafted Flicker",
    "Flicker Intergrade",
    "Red-shafted Flicker",
    "Gilded Flicker",
    "Pileated Woodpecker",
    "Ivory-billed Woodpecker",
    "Crested Caracara",
    "Audubon's Crested Caracara",
    "Eurasian Kestrel",
    "American Kestrel",
    "Merlin",
    "Aplomado Falcon",
    "Gyrfalcon",
    "Peregrine Falcon",
    "Prairie Falcon",
    "Blue-crowned Lorikeet",
    "Monk Parakeet",
    "Black-headed Parakeet",
    "Orange-fronted Parakeet",
    "Brown-throated Parakeet",
    "Hispaniolan Parakeet",
    "Thick-billed Parrot",
    "Cherry-head Conure",
    "Hispaniolan Parrot",
    "Puerto Rican Parrot",
    "Red-crowned Parrot",
    "Orange-winged Amazon",
    "Northern Beardless-Tyrannulet",
    "Jamaican Elaenia",
    "Greenish Elaenia",
    "Caribbean Elaenia",
    "Yellow-bellied Elaenia",
    "Greater Antillean Elaenia",
    "Olive-sided Flycatcher",
    "Greater Pewee",
    "Western Wood-Pewee",
    "Eastern Wood-Pewee",
    "Cuban Pewee",
    "Jamaican Pewee",
    "Hispaniolan Pewee",
    "Lesser Antillean Pewee",
    "Yellow-bellied Flycatcher",
    "Acadian Flycatcher",
    "Alder Flycatcher",
    "Traill's Flycatcher",
    "Willow Flycatcher",
    "Southwestern Willow Flycatcher",
    "Least Flycatcher",
    "Hammond's Flycatcher",
    "Gray Flycatcher",
    "Dusky Flycatcher",
    "Pacific-slope Flycatcher",
    "Western Flycatcher",
    "Cordilleran Flycatcher",
    "Buff-breasted Flycatcher",
    "Unidentified Empidonax",
    "Black Phoebe",
    "Eastern Phoebe",
    "Say's Phoebe",
    "Vermilion Flycatcher",
    "Sad Flycatcher",
    "Dusky-capped Flycatcher",
    "Ash-throated Flycatcher",
    "Nutting's Flycatcher",
    "Great Crested Flycatcher",
    "Brown-crested Flycatcher",
    "La Sagra's Flycatcher",
    "Stolid Flycatcher",
    "Puerto Rican Flycatcher",
    "Lesser Antillean Flycatcher",
    "Great Kiskadee",
    "Sulphur-bellied Flycatcher",
    "Tropical Kingbird",
    "Couch's Kingbird",
    "Cassin's Kingbird",
    "Thick-billed Kingbird",
    "Western Kingbird",
    "Eastern Kingbird",
    "Gray Kingbird",
    "Loggerhead Kingbird",
    "Scissor-tailed Flycatcher",
    "Fork-tailed Flycatcher",
    "Rose-throated Becard",
    "Cardinal Honeyeater",
    "Wattled Honeyeater",
    "Micronesian Honeyeater",
    "Brown Shrike",
    "Loggerhead Shrike",
    "San Clemente Loggerhead Shrike",
    "Northern Shrike",
    "White-eyed Vireo",
    "Thick-billed Vireo",
    "Jamaican Vireo",
    "Puerto Rican Vireo",
    "Bell's Vireo",
    "Least Bell's Vireo",
    "Black-capped Vireo",
    "Gray Vireo",
    "Yellow-throated Vireo",
    "Plumbeous Vireo",
    "Cassin's Vireo",
    "Blue-headed Vireo",
    "Solitary Vireo",
    "Hutton's Vireo",
    "Warbling Vireo",
    "Philadelphia Vireo",
    "Red-eyed Vireo",
    "Yellow-green Vireo",
    "Black-whiskered Vireo",
    "Black Drongo",
    "Rufous Fantail",
    "Fiji Shrikebill",
    "Tinian Monarch",
    "Canada Jay",
    "Brown Jay",
    "Green Jay",
    "Pinyon Jay",
    "Steller's Jay",
    "Blue Jay",
    "Florida Scrub-Jay",
    "California Scrub-Jay",
    "Island Scrub-Jay",
    "Western Scrub-Jay",
    "Woodhouse's Scrub-Jay",
    "Mexican Jay",
    "Clark's Nutcracker",
    "Black-billed Magpie",
    "Yellow-billed Magpie",
    "Mariana Crow",
    "American Crow",
    "Northwestern Crow",
    "White-necked Crow",
    "Jamaican Crow",
    "Tamaulipas Crow",
    "Fish Crow",
    "Hawaiian Crow",
    "Chihuahuan Raven",
    "Common Raven",
    "Kauai Elepaio",
    "Oahu Elepaio",
    "Hawaii Elepaio",
    "Eurasian Skylark",
    "Horned Lark",
    "Streaked Horned Lark",
    "Purple Martin",
    "Caribbean Martin",
    "Gray-breasted Martin",
    "Tree Swallow",
    "Violet-green Swallow",
    "Bahama Swallow",
    "Northern Rough-winged Swallow",
    "Bank Swallow",
    "Cliff Swallow",
    "Cave Swallow",
    "Barn Swallow",
    "Carolina Chickadee",
    "Black-capped Chickadee",
    "Mountain Chickadee",
    "Mexican Chickadee",
    "Chestnut-backed Chickadee",
    "Boreal Chickadee",
    "Gray-headed Chickadee",
    "Hybrid Chickadee",
    "Varied Tit",
    "Bridled Titmouse",
    "Oak Titmouse",
    "Juniper Titmouse",
    "Tufted Titmouse",
    "Plain Titmouse",
    "Black-crested Titmouse",
    "Verdin",
    "Bushtit",
    "Red-breasted Nuthatch",
    "White-breasted Nuthatch",
    "Pygmy Nuthatch",
    "Brown-headed Nuthatch",
    "Brown Creeper",
    "Rock Wren",
    "Canyon Wren",
    "House Wren",
    "Southern House Wren",
    "Pacific Wren",
    "Winter Wren",
    "Sedge Wren",
    "Marsh Wren",
    "Carolina Wren",
    "Bewick's Wren",
    "Cactus Wren",
    "Blue-gray Gnatcatcher",
    "California Gnatcatcher",
    "Baja Gnatcatcher",
    "Black-tailed Gnatcatcher",
    "Black-capped Gnatcatcher",
    "American Dipper",
    "Red-vented Bulbul",
    "Red-whiskered Bulbul",
    "Golden-crowned Kinglet",
    "Ruby-crowned Kinglet",
    "Japanese Bush-Warbler",
    "Wood Warbler",
    "Dusky Warbler",
    "Arctic Warbler",
    "Wrentit",
    "Japanese White-eye",
    "Greater Necklaced Laughingthrush",
    "Hwamei",
    "Red-billed Leiothrix",
    "Millerbird",
    "Nightingale Reed Warbler",
    "Middendorff's Grasshopper-Warbler",
    "Golden White-eye",
    "Rota White-eye",
    "Bridled White-eye",
    "Lanceolated Warbler",
    "Gray-streaked Flycatcher",
    "Dark-sided Flycatcher",
    "White-rumped Shama",
    "Siberian Rubythroat",
    "Bluethroat",
    "Red-flanked Bluetail",
    "Taiga Flycatcher",
    "Northern Wheatear",
    "Eastern Bluebird",
    "Western Bluebird",
    "Mountain Bluebird",
    "Hybrid Western/Mountain Bluebird",
    "Townsend's Solitaire",
    "Rufous-throated Solitaire",
    "Kamao",
    "Olomao",
    "Omao",
    "Puaiohi",
    "Orange-billed Nightingale-Thrush",
    "Veery",
    "Gray-cheeked Thrush",
    "Bicknell's Thrush",
    "Unidentified Gray-cheeked/Bicknell's Thrush",
    "Swainson's Thrush",
    "Hermit Thrush",
    "Wood Thrush",
    "Eyebrowed Thrush",
    "Dusky Thrush",
    "Fieldfare",
    "Redwing",
    "Clay-colored Thrush",
    "White-eyed Thrush",
    "Rufous-backed Robin",
    "American Robin",
    "White-chinned Thrush",
    "Red-legged Thrush",
    "Varied Thrush",
    "Aztec Thrush",
    "Gray Catbird",
    "Pearly-eyed Thrasher",
    "Brown Trembler",
    "Curve-billed Thrasher",
    "Brown Thrasher",
    "Long-billed Thrasher",
    "Bendire's Thrasher",
    "California Thrasher",
    "LeConte's Thrasher",
    "Crissal Thrasher",
    "Sage Thrasher",
    "Bahama Mockingbird",
    "Tropical Mockingbird",
    "Northern Mockingbird",
    "Blue Mockingbird",
    "Micronesian Starling",
    "Polynesian Starling",
    "Samoan Starling",
    "European Starling",
    "Crested Myna",
    "Javan Myna",
    "Jungle Myna",
    "Common Myna",
    "Hill Myna",
    "Siberian Accentor",
    "Eastern Yellow Wagtail",
    "Gray Wagtail",
    "White Wagtail",
    "Black-backed Wagtail",
    "Olive-backed Pipit",
    "Pechora Pipit",
    "Red-throated Pipit",
    "American Pipit",
    "Sprague's Pipit",
    "Bohemian Waxwing",
    "Cedar Waxwing",
    "Kauai Oo",
    "Bishop's Oo",
    "Phainopepla",
    "Olive Warbler",
    "Lapland Longspur",
    "Chestnut-collared Longspur",
    "Smith's Longspur",
    "McCown's Longspur",
    "Snow Bunting",
    "McKay's Bunting",
    "Ovenbird",
    "Worm-eating Warbler",
    "Louisiana Waterthrush",
    "Northern Waterthrush",
    "Golden-winged Warbler",
    "Blue-winged Warbler",
    "Brewster's Warbler",
    "Lawrence's Warbler",
    "Golden-winged x Blue-winged Warbler Hybrid",
    "Black-and-white Warbler",
    "Prothonotary Warbler",
    "Swainson's Warbler",
    "Tennessee Warbler",
    "Orange-crowned Warbler",
    "Colima Warbler",
    "Lucy's Warbler",
    "Nashville Warbler",
    "Virginia's Warbler",
    "Connecticut Warbler",
    "Gray-crowned Yellowthroat",
    "MacGillivray's Warbler",
    "Mourning Warbler",
    "Kentucky Warbler",
    "Bahama Yellowthroat",
    "Common Yellowthroat",
    "Elfin-woods Warbler",
    "Arrowhead Warbler",
    "Hooded Warbler",
    "American Redstart",
    "Kirtland's Warbler",
    "Cape May Warbler",
    "Cerulean Warbler",
    "Northern Parula",
    "Tropical Parula",
    "Magnolia Warbler",
    "Bay-breasted Warbler",
    "Blackburnian Warbler",
    "Yellow Warbler",
    "Chestnut-sided Warbler",
    "Blackpoll Warbler",
    "Black-throated Blue Warbler",
    "Western Palm Warbler",
    "Yellow Palm Warbler",
    "Olive-capped Warbler",
    "Pine Warbler",
    "Myrtle Warbler",
    "Unknown Yellow-rumped Warbler",
    "Audubon's Warbler",
    "Yellow-throated Warbler",
    "Sutton's Warbler",
    "Prairie Warbler",
    "Adelaide's Warbler",
    "Barbuda Warbler",
    "St. Lucia Warbler",
    "Grace's Warbler",
    "Black-throated Gray Warbler",
    "Townsend's Warbler",
    "Townsend's X Hermit Warbler Hybrid",
    "Hermit Warbler",
    "Golden-cheeked Warbler",
    "Black-throated Green Warbler",
    "Fan-tailed Warbler",
    "Rufous-capped Warbler",
    "Golden-crowned Warbler",
    "Canada Warbler",
    "Wilson's Warbler",
    "Red-faced Warbler",
    "Painted Redstart",
    "Slate-throated Redstart",
    "Yellow-breasted Chat",
    "Hybrid Warbler",
    "Bananaquit",
    "Red-crested Cardinal",
    "Yellow-billed Cardinal",
    "Puerto Rican Tanager",
    "Western Spindalis",
    "Hispaniolan Spindalis",
    "Puerto Rican Spindalis",
    "Jamaican Spindalis",
    "Blue-black Grassquit",
    "White-collared Seedeater",
    "Yellow-bellied Seedeater",
    "Cuban Grassquit",
    "Yellow-faced Grassquit",
    "Black-faced Grassquit",
    "Yellow-shouldered Grassquit",
    "Puerto Rican Bullfinch",
    "Greater Antillean Bullfinch",
    "Lesser Antillean Bullfinch",
    "Orangequit",
    "Saffron Finch",
    "Olive Sparrow",
    "Green-tailed Towhee",
    "Spotted Towhee",
    "Eastern Towhee",
    "Unidentified Rufous-sided Towhee",
    "Hybrid Towhee",
    "Inyo California Towhee",
    "Rufous-crowned Sparrow",
    "Canyon Towhee",
    "California Towhee",
    "Abert's Towhee",
    "Rufous-winged Sparrow",
    "Botteri's Sparrow",
    "Cassin's Sparrow",
    "Bachman's Sparrow",
    "American Tree Sparrow",
    "Chipping Sparrow",
    "Clay-colored Sparrow",
    "Brewer's Sparrow",
    "Field Sparrow",
    "Worthen's Sparrow",
    "Black-chinned Sparrow",
    "Vesper Sparrow",
    "Lark Sparrow",
    "Five-striped Sparrow",
    "Black-throated Sparrow",
    "Sagebrush Sparrow",
    "Unspecified Sage Sparrow",
    "San Clemente Bell's Sparrow",
    "Bell's Sparrow",
    "Lark Bunting",
    "Savannah Sparrow",
    "Ipswich Sparrow",
    "Belding's Savannah Sparrow",
    "Large-billed Sparrow",
    "Grasshopper Sparrow",
    "Florida Grasshopper Sparrow",
    "Baird's Sparrow",
    "Henslow's Sparrow",
    "LeConte's Sparrow",
    "Nelson's Sparrow",
    "Saltmarsh Sparrow",
    "Unidentified Sharp-tailed Sparrow",
    "Seaside Sparrow",
    "Dusky Seaside Sparrow",
    "Cape Sable Seaside Sparrow",
    "Fox Sparrow",
    "Song Sparrow",
    "Lincoln's Sparrow",
    "Swamp Sparrow",
    "Rufous-collared Sparrow",
    "White-throated Sparrow",
    "Harris's Sparrow",
    "White-crowned Sparrow",
    "Eastern White-crowned Sparrow",
    "Mountain White-crowned Sparrow",
    "Puget Sound White-crowned Sparrow",
    "Gambel's White-crowned Sparrow",
    "Nuttall's White-crowned Sparrow",
    "Golden-crowned Sparrow",
    "White-winged Junco",
    "Zonotrichia Sparrow Hybrid",
    "Slate-colored Junco",
    "Oregon Junco",
    "Unidentified Dark-eyed Junco",
    "Gray-headed Junco",
    "Yellow-eyed Junco",
    "Little Bunting",
    "Rustic Bunting",
    "Gray Bunting",
    "Pallas's Bunting",
    "Reed Bunting",
    "Hepatic Tanager",
    "Summer Tanager",
    "Scarlet Tanager",
    "Western Tanager",
    "Flame-colored Tanager",
    "Northern Cardinal",
    "Pyrrhuloxia",
    "Yellow Grosbeak",
    "Rose-breasted Grosbeak",
    "Black-headed Grosbeak",
    "Blue Bunting",
    "Blue Grosbeak",
    "Lazuli Bunting",
    "Indigo X Lazuli Bunting Hybrid",
    "Indigo Bunting",
    "Varied Bunting",
    "Painted Bunting",
    "Dickcissel",
    "Bobolink",
    "Red-winged Blackbird",
    "Tricolored Blackbird",
    "Tawny-shouldered Blackbird",
    "Yellow-shouldered Blackbird",
    "Eastern Meadowlark",
    "Western Meadowlark",
    "Yellow-headed Blackbird",
    "Rusty Blackbird",
    "Brewer's Blackbird",
    "Common Grackle",
    "Boat-tailed Grackle",
    "Great-tailed Grackle",
    "Greater Antillean Grackle",
    "Shiny Cowbird",
    "Bronzed Cowbird",
    "Brown-headed Cowbird",
    "Bahama Oriole",
    "Cuban Oriole",
    "Hispaniolan Oriole",
    "Puerto Rican Oriole",
    "Black-vented Oriole",
    "Black-cowled Oriole",
    "Orchard Oriole",
    "Hooded Oriole",
    "Venezuelan Troupial",
    "Streak-backed Oriole",
    "Bullock's Oriole",
    "Baltimore X Bullock's Oriole Hybrid",
    "Jamaican Oriole",
    "Spot-breasted Oriole",
    "Altamira Oriole",
    "Audubon's Oriole",
    "Baltimore Oriole",
    "Scott's Oriole",
    "Common Chaffinch",
    "Brambling",
    "Jamaican Euphonia",
    "Antillean Euphonia",
    "Gray-crowned Rosy-Finch",
    "Black Rosy-Finch",
    "Brown-capped Rosy-Finch",
    "Pine Grosbeak",
    "Eurasian Bullfinch",
    "Laysan Finch",
    "Nihoa Finch",
    "Ou",
    "Palila",
    "Maui Parrotbill",
    "Hawaii Amakihi",
    "Oahu Amakihi",
    "Kauai Amakihi",
    "Oahu Akialoa",
    "Nukupuu",
    "Akiapolaau",
    "Anianiau",
    "Akikiki",
    "Oahu Alauahio",
    "Kakawahie",
    "Maui Alauahio",
    "Hawaii Creeper",
    "Akekee",
    "Akepa",
    "Iiwi",
    "Akohekohe",
    "Apapane",
    "Poo-uli",
    "Common Rosefinch",
    "House Finch",
    "Purple Finch",
    "Cassin's Finch",
    "Red Crossbill",
    "Cassia Crossbill",
    "White-winged Crossbill",
    "Common Redpoll",
    "Hoary Redpoll",
    "Unidentified Common/Hoary Redpoll",
    "Pine Siskin",
    "Red Siskin",
    "Lesser Goldfinch",
    "Lawrence's Goldfinch",
    "American Goldfinch",
    "European Goldfinch",
    "Oriental Greenfinch",
    "Yellow-fronted Canary",
    "Common Canary",
    "Evening Grosbeak",
    "Hawfinch",
    "House Sparrow",
    "Eurasian Tree Sparrow",
    "Yellow-crowned Bishop",
    "Northern Red Bishop",
    "Red-cheeked Cordonbleu",
    "Lavender Waxbill",
    "Orange-cheeked Waxbill",
    "Black-rumped Waxbill",
    "Common Waxbill",
    "Red Avadavat",
    "Bronze Mannikin",
    "African Silverbill",
    "Java Sparrow",
    "Scaly-breasted Munia",
    "Tricolored Munia",
    "Pin-tailed Whydah"
];

let randomNumber = Math.floor(Math.random() * birdCodes.length);
const answerCode = birdCodes[randomNumber];
const answerName = birdNames[randomNumber];

const answerCodeDisp = document.querySelector(".answerCodeDisp");
const previousGuesses = document.querySelector(".previousGuesses");
const guesses = document.querySelector(".guesses");
const lastResult = document.querySelector(".lastResult");
const guessSubmit = document.querySelector(".guessSubmit");
const guessField = document.querySelector(".guessField");
let guessCount = 1;
let maxGuesses = birdCodes.length;
let resetButton;

guesses.style.whiteSpace = "pre";

answerCodeDisp.textContent = 'Code: ' + answerCode;

function checkGuess() {
    const userGuess = guessField.value;
    if (guessCount == 1) {
        previousGuesses.textContent = 'Previous guesses:';
    }

    guesses.textContent = userGuess + '\n' + guesses.textContent;

    if (userGuess.toLowerCase() == answerName.toLowerCase()) {
        lastResult.textContent = 'Correct!';
        lastResult.style.color = 'green';
        setGameOver();
    } else {
        lastResult.textContent = 'WRONG!';
        lastResult.style.color = 'red';
    }

    guessCount++;
    guessField.value = '';
    guessField.focus();

}

guessSubmit.addEventListener('click', checkGuess);

function setGameOver() {
    guessField.disabled = true;
    guessSubmit.disabled = true;
    resetButton = document.createElement('button');
    resetButton.textContent = 'Start new game';
    document.body.appendChild(resetButton);
    resetButton.addEventListener('click', resetGame);
}

function resetGame() {
    guessCount = 1;
    const resetParas = document.querySelectorAll('.resultParas p');
    for (const resetPara of resetParas) {
        resetPara.textContent = '';
    }

    resetButton.parentNode.removeChild(resetButton);
    guessField.disabled = false;
    guessSubmit.disabled = false;
    guessField.value = '';
    guessField.focus();
    lastResult.style.color = 'black';
    randomNumber = Math.floor(Math.random() * birdCodes.length);
}